unpackaged/objects/AccountEdit__c.object
<CustomObject>
    <description>Contains Temporary Data Used to Update Accounts via Trigger</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountEdits</relationshipLabel>
        <relationshipName>AccountEdits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AccountEdit</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountEdits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/CalEPAPartnerAgencyTriggerHandlerTests.cls
@isTest
public with sharing class CalEPAPartnerAgencyTriggerHandlerTests 
{
    public static testMethod void TestDeleteAccountRemoveAccountEdits()
    {
        //Arrange
        integer expected = 0;
        Account testAccount = UnitTestHelper.CreateTestAccount();
        string testAccountId = testAccount.Id;
        AccountEdit__c accountEdit = new AccountEdit__c();
        accountEdit.Account__c = testAccount.Id;
        insert accountEdit;

        //Act
        Test.startTest();
        delete testAccount;
        Test.stopTest();
        List<AccountEdit__c> edits = [SELECT Id FROM AccountEdit__c WHERE Account__c=: testAccountId ];
        integer actual = edits.Size();
        //Assert

        System.AssertEquals(expected, actual);
    }
}