unpackaged/objects/AccountEdit__c.object
<CustomObject>
    <description>Contains Temporary Data Used to Update Accounts via Trigger</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountEdits</relationshipLabel>
        <relationshipName>AccountEdits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AccountEdit</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountEdits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/CalEPAPartnerAgencyAccountTriggerHandler.cls
public with sharing class CalEPAPartnerAgencyAccountTriggerHandler extends TriggerHandler 
{
    public CalEPAPartnerAgencyAccountTriggerHandler() 
    {
        
    }
    protected override void beforeDelete()
    {
        List<Id> accountIds = new List<Id>();
        for(Account account: (List<Account>)Trigger.Old) 
        {
            accountIds.Add(account.Id);
        }
        
        List<AccountEdit__c> accountEditsToDelete = [SELECT Id FROM AccountEdit__c WHERE Account__c in: accountIds];
        delete accountEditsToDelete;
    }
}