unpackaged/objects/CAMS_Assignment__c.object
<CustomObject>
    <description>Custom object for CAMS app. Creates a record for tracking correspondence....</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Detailed notes and comments regarding the assignment ......Added by Susmita</description>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>CAMS-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CAMS_Task__c.object
<CustomObject>
    <description>Task associated to CAMS Assignment.</description>
    <fields>
        <fullName>CAMS_Assignment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup for CAMS Assignment.</description>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>CAMS_Tasks2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>CAMS Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/File__c.object
<CustomObject>
    <description>CAMS File</description>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>Files</relationshipLabel>
        <relationshipName>Files</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CAMS_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CAMS Task</label>
        <referenceTo>CAMS_Task__c</referenceTo>
        <relationshipLabel>Files</relationshipLabel>
        <relationshipName>Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Doc_Id__c</fullName>
        <label>Doc Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Uploaded_To__c</fullName>
        <label>Uploaded To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>File</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CAMSFileUploadController.cls
public class CAMSFileUploadController 
{
    @AuraEnabled 
    public static boolean SaveCAMSFile(id recordId, string name, string description, id contentVersionId, string fin)	 
	{  
		try 
		{
            if(string.isBlank(fin))
            {
                fin='false';
            }
            System.Debug('fin:  ' + fin);
            ContentVersion contentVersion = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersionId LIMIT 1];
            Schema.SObjectType type = recordId.getsobjecttype();
            if(type.getDescribe().getName() == 'CAMS_Assignment__c')
            {
                CAMS_Assignment__c assignment = [SELECT Id, Name FROM CAMS_Assignment__c WHERE Id=: recordId];
                File__c newFile = new File__c();
                newFile.assignment__c = assignment.id;
                newFile.uploaded_to__c = assignment.name;
                newFile.Name = contentVersion.Title;
                newFile.Description__c = description;
                newFile.Doc_Id__c = contentVersion.ContentDocumentId;
                newFile.Final__c = Boolean.valueOf(fin);
                System.Debug('newFile.Final__c:  ' + newFile.Final__c);
                insert newFile;
            }
            else
            {
                if(type.getDescribe().getName() == 'CAMS_Task__c')
                {
                    CAMS_Task__c task = [SELECT Id, Name, CAMS_Assignment__c FROM CAMS_Task__c WHERE Id=: recordId];
                    File__c newFile = new File__c();
                    newFile.assignment__c = task.CAMS_Assignment__c;
                    newFile.uploaded_to__c = task.Name;
                    newFile.Name = contentVersion.Title;
                    newFile.Description__c = description;
                    newFile.Doc_Id__c = contentVersion.ContentDocumentId;
                    newFile.Final__c = Boolean.valueOf(fin);
                    System.Debug('newFile.Final__c:  ' + newFile.Final__c);
                    insert newFile;
                }
            }
            return true;
    	}
		catch (DMLException de) 
		{
			String message = de.getDmlMessage(0);
			throw new AuraHandledException(message);    
		} 
		catch (Exception e) 
		{
			throw new AuraHandledException(e.getMessage());    
		}
    	finally 
		{
        	// Something executed whether there was an error or not
    	}
    }

    @AuraEnabled
    public static Id SaveTheFile(Id parentId, String fileName, String base64Data, String contentType) 
    { 
        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
        ContentVersion contentVersion = new ContentVersion(versionData = EncodingUtil.base64Decode(base64Data), IsMajorVersion=false, title = fileName, pathOnClient =  '/' + fileName, FirstPublishLocationId = parentId);
        insert contentVersion; 
        return contentVersion.Id;
    }

    @AuraEnabled
    public static Id SaveTheChunk(Id parentId, String fileName, String base64Data, String contentType, String fileId) 
    { 
        try 
		{
            if (fileId == '') 
            {
                fileId = SaveTheFile(parentId, fileName, base64Data, contentType);
            } 
            else 
            {
                AppendToFile(fileId, base64Data);
            }
            return Id.valueOf(fileId);
        }
		catch (DMLException de) 
		{
			String message = de.getDmlMessage(0);
			throw new AuraHandledException(message);    
		} 
		catch (Exception e) 
		{
			throw new AuraHandledException(e.getMessage());    
		}
    	finally 
		{
        	// Something executed whether there was an error or not
    	}
    }

    private static void AppendToFile(Id fileId, String base64Data) 
    {
        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
        ContentVersion contentVersion = [SELECT Id, versionData FROM ContentVersion WHERE Id = :fileId];
        String existingBody = EncodingUtil.base64Encode(contentVersion.versionData);
        contentVersion.versionData = EncodingUtil.base64Decode(existingBody + base64Data); 
        update contentVersion;   
    }
}