unpackaged/objects/CAMS_Assignment__c.object
<CustomObject>
    <description>Custom object for CAMS app. Creates a record for tracking correspondence....</description>
    <label>Assignment</label>
    <nameField>
        <displayFormat>CAMS-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CAMS_Note__c.object
<CustomObject>
    <fields>
        <fullName>CAMS_Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>CAMS Notes</relationshipLabel>
        <relationshipName>CAMS_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CAMS_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>CAMS_Task__c</referenceTo>
        <relationshipLabel>CAMS Notes</relationshipLabel>
        <relationshipName>CAMS_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Uploaded_To__c</fullName>
        <label>Uploaded To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CAMS Note</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CAMS Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/CAMS_Task__c.object
<CustomObject>
    <description>Task associated to CAMS Assignment.</description>
    <fields>
        <fullName>CAMS_Assignment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup for CAMS Assignment.</description>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>CAMS_Tasks2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>CAMS Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/CAMSNoteCreateController.cls
public class CAMSNoteCreateController 
{
    @AuraEnabled 
    public static boolean SaveCAMSNote(id recordId, string subject, string content)	 
	{  
		try 
		{
            CAMS_Note__c note = new CAMS_Note__c();
            note.Name = subject;
            note.Content__c = content;
            Schema.SObjectType type = recordId.getsobjecttype();
            if(type.getDescribe().getName() == 'CAMS_Assignment__c')
            {
                CAMS_Assignment__c assignment = [SELECT Id, Name FROM CAMS_Assignment__c WHERE Id=: recordId];
                note.CAMS_Assignment__c = assignment.Id;
                note.Uploaded_To__c = assignment.Name;
            }
            else
            {
                if(type.getDescribe().getName() == 'CAMS_Task__c')
                {
                    CAMS_Task__c task = [SELECT Id, Name, CAMS_Assignment__c FROM CAMS_Task__c WHERE Id=: recordId];
                    note.CAMS_Assignment__c = task.CAMS_Assignment__c;
                    note.CAMS_Task__c = task.Id;
                    note.Uploaded_To__c = task.Name;
                }
            }
            insert note;
            return true;
    	}
		catch (DMLException de) 
		{
			String message = de.getDmlMessage(0);
			throw new AuraHandledException(message);    
		} 
		catch (Exception e) 
		{
			throw new AuraHandledException(e.getMessage());    
		}
    	finally 
		{
        	// Something executed whether there was an error or not
    	}
    }
}