unpackaged/objects/CAMS_Assignment__c.object
<CustomObject>
    <description>Custom object for CAMS app. Creates a record for tracking correspondence....</description>
    <fields>
        <fullName>BDO_Suborganization__c</fullName>
        <label>Division, Office or Program</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BDO__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Climate Policy</fullName>
                </value>
                <value>
                    <fullName>Environmental Policy</fullName>
                </value>
                <value>
                    <fullName>Health and Public Policy</fullName>
                </value>
                <value>
                    <fullName>Legislative Affairs</fullName>
                </value>
                <value>
                    <fullName>Law Enforcement and Counsel</fullName>
                </value>
                <value>
                    <fullName>Environmental Justice and Tribal</fullName>
                </value>
                <value>
                    <fullName>Fiscal and Admin Programs</fullName>
                </value>
                <value>
                    <fullName>Unified Program</fullName>
                </value>
                <value>
                    <fullName>Chief Information Officer</fullName>
                </value>
                <value>
                    <fullName>PRA</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Executive Office</fullName>
                </value>
                <value>
                    <fullName>Legislative Office</fullName>
                </value>
                <value>
                    <fullName>Legal Office</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Secretary</fullName>
                    <isActive>false</isActive>
                    <label>Secretary</label>
                </value>
                <value>
                    <fullName>Undersecretary</fullName>
                    <isActive>false</isActive>
                    <label>Undersecretary</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BDO__c</fullName>
        <defaultValue>CASE($User.BDO__c, 
&quot;ARB&quot;, &quot;ARB&quot;,
&quot;CalRecycle&quot;,&quot;CalRecycle&quot;,
&quot;DTSC&quot;,&quot;DTSC&quot;,
&quot;DPR&quot;,&quot;DPR&quot;,
&quot;SWRCB&quot;,&quot;SWRCB&quot;,
&quot;OEHHA&quot;,&quot;OEHHA&quot;,
&quot;Agency&quot;)</defaultValue>
        <description>Defines the Department, Board or Office that initiated the assignment.</description>
        <label>BDO</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ARB</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>CalRecycle</fullName>
                </value>
                <value>
                    <fullName>DPR</fullName>
                </value>
                <value>
                    <fullName>DTSC</fullName>
                </value>
                <value>
                    <fullName>OEHHA</fullName>
                </value>
                <value>
                    <fullName>SWRCB</fullName>
                </value>
                <value>
                    <fullName>OOS</fullName>
                    <isActive>false</isActive>
                    <label>OOS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Pending&quot;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Back to BDO</fullName>
                    <isActive>false</isActive>
                    <label>Back to BDO</label>
                </value>
                <value>
                    <fullName>Delegated</fullName>
                    <isActive>false</isActive>
                    <label>Delegated</label>
                </value>
                <value>
                    <fullName>Governor&apos;s Office</fullName>
                    <isActive>false</isActive>
                    <label>Governor&apos;s Office</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>CAMS-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CAMS_Task__c.object
<CustomObject>
    <description>Task associated to CAMS Assignment.</description>
    <fields>
        <fullName>BDO_Suborganization__c</fullName>
        <label>Division, Office or Program</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BDO__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Undersecretary</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Climate Policy</fullName>
                </value>
                <value>
                    <fullName>Environmental Policy</fullName>
                </value>
                <value>
                    <fullName>Health and Public Policy</fullName>
                </value>
                <value>
                    <fullName>Legislative Affairs</fullName>
                </value>
                <value>
                    <fullName>Law Enforcement and Counsel</fullName>
                </value>
                <value>
                    <fullName>Environmental Justice and Tribal</fullName>
                </value>
                <value>
                    <fullName>Fiscal and Admin Programs</fullName>
                </value>
                <value>
                    <fullName>Unified Program</fullName>
                </value>
                <value>
                    <fullName>Chief Information Officer</fullName>
                </value>
                <value>
                    <fullName>PRA</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Executive Office</fullName>
                </value>
                <value>
                    <fullName>Legislative Office</fullName>
                </value>
                <value>
                    <fullName>Legal Office</fullName>
                </value>
                <value>
                    <fullName>Secretary</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BDO__c</fullName>
        <defaultValue>CASE($User.BDO__c, 
&quot;ARB&quot;, &quot;ARB&quot;, 
&quot;CalRecycle&quot;,&quot;CalRecycle&quot;, 
&quot;DTSC&quot;,&quot;DTSC&quot;, 
&quot;DPR&quot;,&quot;DPR&quot;, 
&quot;SWRCB&quot;,&quot;SWRCB&quot;, 
&quot;OEHHA&quot;,&quot;OEHHA&quot;,
&quot;Agency&quot;)</defaultValue>
        <label>Assigned BDO</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>ARB</fullName>
                </value>
                <value>
                    <fullName>CalRecycle</fullName>
                </value>
                <value>
                    <fullName>DPR</fullName>
                </value>
                <value>
                    <fullName>DTSC</fullName>
                </value>
                <value>
                    <fullName>OEHHA</fullName>
                </value>
                <value>
                    <fullName>SWRCB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAMS_Assignment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup for CAMS Assignment.</description>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>CAMS_Tasks2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Predecessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Predecessor on the CAMS Task</description>
        <label>Predecessor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CAMS_Task__c.CAMS_Assignment__c</field>
                <operation>equals</operation>
                <valueField>$Source.CAMS_Assignment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CAMS_Task__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>CAMS_Tasks3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CAMS_Task__c.CAMS_Assignment__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.CAMS_Assignment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CAMS_Task__c</referenceTo>
        <relationshipLabel>Child Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Pending&quot;</defaultValue>
        <description>Status for CAMS Task</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Delegated</fullName>
                </value>
                <value>
                    <fullName>Governors Office</fullName>
                    <label>Governor&apos;s Office</label>
                </value>
                <value>
                    <fullName>Back to Requestor</fullName>
                </value>
                <value>
                    <fullName>Back to Assigned</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Back to BDO</fullName>
                    <isActive>false</isActive>
                    <label>Back to BDO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>CAMS Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/CAMSButtonsController.cls
public with sharing class CAMSButtonsController
{ 
    @AuraEnabled
    public static void AssignTasks2(string aatParam ) 
    {
        //Retrieve Initial Tasks
        CAMS_Assignment__c assgnmnt = [select id, BDO__c, BDO_Suborganization__c, status__c from CAMS_Assignment__C where id = :aatParam];
        List<CAMS_Task__c> initialTasks = [SELECT Id, Status__c, BDO_Suborganization__c, BDO__c FROM CAMS_Task__c WHERE CAMS_Assignment__c =: aatParam AND Predecessor__c = NULL and related_to__r.Predecessor__c = Null and status__c = 'Pending'];
        for(CAMS_Task__c initialTask : initialTasks)
        {
            initialTask.Status__c = 'Delegated';
        }
        update initialTasks;
        string bdoPlusSuborganization = assgnmnt.BDO__c + '_' + assgnmnt.BDO_Suborganization__c.Replace(' ','_');
        assgnmnt.status__c = 'In Progress';
        update assgnmnt;
    }
}