unpackaged/objects/CAMS_History__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>CAMS History</relationshipLabel>
        <relationshipName>CAMS_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name_Id__c</fullName>
        <label>Name Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
                <value>
                    <fullName>Note</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CAMS_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CAMS History</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>CAMS History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAMS History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/File__c.object
<CustomObject>
    <description>CAMS File</description>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>Files</relationshipLabel>
        <relationshipName>Files</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <label>File</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CAMSFileTriggerHandler.cls
public with sharing class CAMSFileTriggerHandler extends TriggerHandler  
{
    protected override void afterDelete()
    {
        List<Id> assignmentIds = new List<Id>();
        List<CAMS_History__c> histories = new List<CAMS_History__c>();
        for(File__c file: (List<File__c>)Trigger.Old) 
        {
            CAMS_History__c history = new CAMS_History__c();
            history.Action__c = 'Delete';
            history.Description__c = 'Deleted';
            history.Name_Id__c = file.Name;
            history.User__c = UserInfo.GetUserId();
            history.Type__c = 'File';
            history.Assignment__c = file.Assignment__c;
            histories.Add(history);            
        }
        insert histories;
    }
}