unpackaged/objects/CAMS_Assignment__c.object
<CustomObject>
    <description>Custom object for CAMS app. Creates a record for tracking correspondence....</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When created, this will default to your name</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BDO_Suborganization__c</fullName>
        <label>Division, Office or Program</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BDO__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Climate Policy</fullName>
                </value>
                <value>
                    <fullName>Environmental Policy</fullName>
                </value>
                <value>
                    <fullName>Health and Public Policy</fullName>
                </value>
                <value>
                    <fullName>Legislative Affairs</fullName>
                </value>
                <value>
                    <fullName>Law Enforcement and Counsel</fullName>
                </value>
                <value>
                    <fullName>Environmental Justice and Tribal</fullName>
                </value>
                <value>
                    <fullName>Fiscal and Admin Programs</fullName>
                </value>
                <value>
                    <fullName>Unified Program</fullName>
                </value>
                <value>
                    <fullName>Chief Information Officer</fullName>
                </value>
                <value>
                    <fullName>PRA</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Executive Office</fullName>
                </value>
                <value>
                    <fullName>Legislative Office</fullName>
                </value>
                <value>
                    <fullName>Legal Office</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Secretary</fullName>
                    <isActive>false</isActive>
                    <label>Secretary</label>
                </value>
                <value>
                    <fullName>Undersecretary</fullName>
                    <isActive>false</isActive>
                    <label>Undersecretary</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BDO__c</fullName>
        <defaultValue>CASE($User.BDO__c, 
&quot;ARB&quot;, &quot;ARB&quot;,
&quot;CalRecycle&quot;,&quot;CalRecycle&quot;,
&quot;DTSC&quot;,&quot;DTSC&quot;,
&quot;DPR&quot;,&quot;DPR&quot;,
&quot;SWRCB&quot;,&quot;SWRCB&quot;,
&quot;OEHHA&quot;,&quot;OEHHA&quot;,
&quot;Agency&quot;)</defaultValue>
        <description>Defines the Department, Board or Office that initiated the assignment.</description>
        <label>BDO</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ARB</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>CalRecycle</fullName>
                </value>
                <value>
                    <fullName>DPR</fullName>
                </value>
                <value>
                    <fullName>DTSC</fullName>
                </value>
                <value>
                    <fullName>OEHHA</fullName>
                </value>
                <value>
                    <fullName>SWRCB</fullName>
                </value>
                <value>
                    <fullName>OOS</fullName>
                    <isActive>false</isActive>
                    <label>OOS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <defaultValue>TODAY() +14</defaultValue>
        <description>Date when correspondence is due back after review and sign</description>
        <label>Due Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Pending&quot;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Back to BDO</fullName>
                    <isActive>false</isActive>
                    <label>Back to BDO</label>
                </value>
                <value>
                    <fullName>Delegated</fullName>
                    <isActive>false</isActive>
                    <label>Delegated</label>
                </value>
                <value>
                    <fullName>Governor&apos;s Office</fullName>
                    <isActive>false</isActive>
                    <label>Governor&apos;s Office</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>CAMS-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CAMS_Task__c.object
<CustomObject>
    <description>Task associated to CAMS Assignment.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BDO_Suborganization__c</fullName>
        <label>Division, Office or Program</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BDO__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Undersecretary</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Climate Policy</fullName>
                </value>
                <value>
                    <fullName>Environmental Policy</fullName>
                </value>
                <value>
                    <fullName>Health and Public Policy</fullName>
                </value>
                <value>
                    <fullName>Legislative Affairs</fullName>
                </value>
                <value>
                    <fullName>Law Enforcement and Counsel</fullName>
                </value>
                <value>
                    <fullName>Environmental Justice and Tribal</fullName>
                </value>
                <value>
                    <fullName>Fiscal and Admin Programs</fullName>
                </value>
                <value>
                    <fullName>Unified Program</fullName>
                </value>
                <value>
                    <fullName>Chief Information Officer</fullName>
                </value>
                <value>
                    <fullName>PRA</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Executive Office</fullName>
                </value>
                <value>
                    <fullName>Legislative Office</fullName>
                </value>
                <value>
                    <fullName>Legal Office</fullName>
                </value>
                <value>
                    <fullName>Secretary</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BDO__c</fullName>
        <defaultValue>CASE($User.BDO__c, 
&quot;ARB&quot;, &quot;ARB&quot;, 
&quot;CalRecycle&quot;,&quot;CalRecycle&quot;, 
&quot;DTSC&quot;,&quot;DTSC&quot;, 
&quot;DPR&quot;,&quot;DPR&quot;, 
&quot;SWRCB&quot;,&quot;SWRCB&quot;, 
&quot;OEHHA&quot;,&quot;OEHHA&quot;,
&quot;Agency&quot;)</defaultValue>
        <label>Assigned BDO</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>ARB</fullName>
                </value>
                <value>
                    <fullName>CalRecycle</fullName>
                </value>
                <value>
                    <fullName>DPR</fullName>
                </value>
                <value>
                    <fullName>DTSC</fullName>
                </value>
                <value>
                    <fullName>OEHHA</fullName>
                </value>
                <value>
                    <fullName>SWRCB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAMS_Assignment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup for CAMS Assignment.</description>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>CAMS_Tasks2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>CAMS Task Due Date</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Instructions__c</fullName>
        <description>Instructions for CAMS Task</description>
        <inlineHelpText>Instructions for CAMS Task</inlineHelpText>
        <label>Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CAMS_Task__c.CAMS_Assignment__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.CAMS_Assignment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CAMS_Task__c</referenceTo>
        <relationshipLabel>Child Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Pending&quot;</defaultValue>
        <description>Status for CAMS Task</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Delegated</fullName>
                </value>
                <value>
                    <fullName>Governors Office</fullName>
                    <label>Governor&apos;s Office</label>
                </value>
                <value>
                    <fullName>Back to Requestor</fullName>
                </value>
                <value>
                    <fullName>Back to Assigned</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Back to BDO</fullName>
                    <isActive>false</isActive>
                    <label>Back to BDO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Concurrent</fullName>
                    <default>true</default>
                    <label>Concurrent</label>
                </value>
                <value>
                    <fullName>Sequential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>CAMS Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <recordTypes>
        <fullName>Concurrent</fullName>
        <active>false</active>
        <label>Concurrent</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>BDO__c</fullName>
        <label>BDO</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ARB</fullName>
                </value>
                <value>
                    <fullName>CalRecycle</fullName>
                </value>
                <value>
                    <fullName>DTSC</fullName>
                </value>
                <value>
                    <fullName>DPR</fullName>
                </value>
                <value>
                    <fullName>SWRCB</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>OEHHA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/CAMSCreateSubtaskController.cls
public class CAMSCreateSubtaskController 
{
	@AuraEnabled 
    public static Date GetParentDueDate(id parentTaskId) 
	{
		CAMS_Task__c task = [SELECT ID, Due_Date__c FROM CAMS_Task__c WHERE Id=:parentTaskId];
		return task.Due_Date__c;
	}

	@AuraEnabled 
    public static List<String> GetBDOs(id parentTaskId) 
	{
		List<String> bdos = new List<String>();
		CAMS_Task__c task = [SELECT ID, BDO__c FROM CAMS_Task__c WHERE Id=:parentTaskId];
		bdos.Add(task.BDO__c);
		return bdos;
		/*
		List<String> bdos = new List<String>();
		Id userId = UserInfo.getUserId();
		User user = [SELECT ID, BDO__c FROM User WHERE Id=:userId];
		if(user.BDO__c == 'Agency')
		{
			bdos.Add('');
			Schema.DescribeFieldResult fieldResult = CAMS_Task__c.BDO__c.getDescribe();
			List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
			for( Schema.PicklistEntry pickListVal : ple)
			{
				bdos.add(pickListVal.getLabel());
			}     
			return bdos;
		}
		else 
		{
			bdos.Add(user.BDO__c);
			bdos.Add('Agency');
			return bdos;
		}
		*/
	}
	
	@AuraEnabled 
    public static List<String> GetStatuses() 
	{
		List<String> statuses = new List<String>();		
		Schema.DescribeFieldResult fieldResult = CAMS_Task__c.Status__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple)
		{
			statuses.add(pickListVal.getLabel());
		}     
		return statuses;
	}
	
	@AuraEnabled 
    public static List<String> GetBDOSuborganizations(string bdo) 
	{
		Id userId = UserInfo.getUserId();
		User user = [SELECT ID, BDO__c FROM User WHERE Id=:userId];
		List<String> suborganizations = new List<String>();
		suborganizations.Add('');
		if(user.BDO__c != 'Agency' && bdo == 'Agency')
		{
			suborganizations.Add('Executive Office');
			suborganizations.Add('Fiscal and Admin Programs');
			return suborganizations;
		}
		else
		{
			PicklistFieldController controller = new PicklistFieldController();
			Map<String,List<String>> valueMap = controller.getDependentOptionsImpl('CAMS_Task__c','BDO__c','BDO_Suborganization__c');
			System.Debug('valueMap:  ' + valueMap);
			for(String contr : valueMap.keySet())
			{
				if(contr==bdo)
				{
					for(String v : valueMap.get(contr))
					{
						suborganizations.Add(v);
					}
				}
			}
			return suborganizations;
		}
	}	  
	
	@AuraEnabled 
    public static List<User> GetQueueUsers(string bdo, string suborganization) 
	{
		string groupName = bdo + '_' + suborganization.Replace(' ','_');
		List<Group> groups = [SELECT Id FROM Group WHERE DeveloperName =: groupName AND (Type='Queue' OR Type='Regular')];
		List<Id> groupIds = new List<Id>();
		for(Group g : groups)
		{
			groupIds.Add(g.Id);
		}
		List<GroupMember> members = new List<GroupMember>(); 
		for(GroupMember sgm : [SELECT UserOrGroupId FROM GroupMember WHERE GroupId in: groupIds ])
		{
			members.Add(sgm);			
		}
		List<Id> userIds = new List<Id>();
		for(GroupMember groupMember : members)
		{
			if(string.ValueOf(groupMember.UserOrGroupId).StartsWith('005'))
			{
				if(!userIds.contains(groupMember.UserOrGroupId))
				{
					userIds.Add(groupMember.UserOrGroupId);
				}
			}
		}
		List<User> users = new List<User>();
		users.Add(new User());
		List<User> retrievedUsers = [SELECT Id, Name FROM User WHERE Id in: userIds];
		for(User user : retrievedUsers)
		{
			users.Add(user);
		}
		return users;
	}

	@AuraEnabled 
    public static CAMS_Task__c SaveChildTask(id parentTaskId, string bdo, string suborganization, id assignedTo, string dueDate, string status, string instructions)	 
	{  
		try 
		{
			CAMS_Task__c parentTask = [SELECT ID, CAMS_Assignment__c FROM CAMS_Task__c WHERE Id =: parentTaskId];
			CAMS_Task__c task = new CAMS_Task__c();
			task.CAMS_Assignment__c = parentTask.CAMS_Assignment__c;
			task.Related_To__c = parentTask.Id;
			task.BDO__c = bdo;
			task.BDO_Suborganization__c = suborganization;
			task.Assigned_To__c = assignedTo; 
			if(!string.IsBlank(dueDate))
			{
				task.Due_Date__c = date.parse(dueDate);
			}
			task.Status__c = status;
			task.Instructions__c = instructions;
			task.Task_Type__c = 'Concurrent';
			upsert task;
			return task;
    	}
		catch (DMLException de) 
		{
			System.Debug('de:  ' + de);
			throw new AuraHandledException(de.getMessage());    
		} 
		catch (Exception e) 
		{
			System.Debug('e:  ' + e);
			throw new AuraHandledException(e.getMessage());    
		}
   }
}