unpackaged/objects/CAMS_Assignment__c.object
<CustomObject>
    <description>Custom object for CAMS app. Creates a record for tracking correspondence....</description>
    <fields>
        <fullName>BDO_Suborganization__c</fullName>
        <label>Division, Office or Program</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BDO__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Climate Policy</fullName>
                </value>
                <value>
                    <fullName>Environmental Policy</fullName>
                </value>
                <value>
                    <fullName>Health and Public Policy</fullName>
                </value>
                <value>
                    <fullName>Legislative Affairs</fullName>
                </value>
                <value>
                    <fullName>Law Enforcement and Counsel</fullName>
                </value>
                <value>
                    <fullName>Environmental Justice and Tribal</fullName>
                </value>
                <value>
                    <fullName>Fiscal and Admin Programs</fullName>
                </value>
                <value>
                    <fullName>Unified Program</fullName>
                </value>
                <value>
                    <fullName>Chief Information Officer</fullName>
                </value>
                <value>
                    <fullName>PRA</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Executive Office</fullName>
                </value>
                <value>
                    <fullName>Legislative Office</fullName>
                </value>
                <value>
                    <fullName>Legal Office</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Secretary</fullName>
                    <isActive>false</isActive>
                    <label>Secretary</label>
                </value>
                <value>
                    <fullName>Undersecretary</fullName>
                    <isActive>false</isActive>
                    <label>Undersecretary</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BDO__c</fullName>
        <defaultValue>CASE($User.BDO__c, 
&quot;ARB&quot;, &quot;ARB&quot;,
&quot;CalRecycle&quot;,&quot;CalRecycle&quot;,
&quot;DTSC&quot;,&quot;DTSC&quot;,
&quot;DPR&quot;,&quot;DPR&quot;,
&quot;SWRCB&quot;,&quot;SWRCB&quot;,
&quot;OEHHA&quot;,&quot;OEHHA&quot;,
&quot;Agency&quot;)</defaultValue>
        <description>Defines the Department, Board or Office that initiated the assignment.</description>
        <label>BDO</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ARB</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>CalRecycle</fullName>
                </value>
                <value>
                    <fullName>DPR</fullName>
                </value>
                <value>
                    <fullName>DTSC</fullName>
                </value>
                <value>
                    <fullName>OEHHA</fullName>
                </value>
                <value>
                    <fullName>SWRCB</fullName>
                </value>
                <value>
                    <fullName>OOS</fullName>
                    <isActive>false</isActive>
                    <label>OOS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <defaultValue>TODAY() +14</defaultValue>
        <description>Date when correspondence is due back after review and sign</description>
        <label>Due Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of Correspondence</description>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>CAMS-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <recordTypes>
        <fullName>Controlled_Correspondence</fullName>
        <active>true</active>
        <label>4 Controlled Correspondence</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CAMS_Task__c.object
<CustomObject>
    <description>Task associated to CAMS Assignment.</description>
    <fields>
        <fullName>BDO_Suborganization__c</fullName>
        <label>Division, Office or Program</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BDO__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Undersecretary</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Climate Policy</fullName>
                </value>
                <value>
                    <fullName>Environmental Policy</fullName>
                </value>
                <value>
                    <fullName>Health and Public Policy</fullName>
                </value>
                <value>
                    <fullName>Legislative Affairs</fullName>
                </value>
                <value>
                    <fullName>Law Enforcement and Counsel</fullName>
                </value>
                <value>
                    <fullName>Environmental Justice and Tribal</fullName>
                </value>
                <value>
                    <fullName>Fiscal and Admin Programs</fullName>
                </value>
                <value>
                    <fullName>Unified Program</fullName>
                </value>
                <value>
                    <fullName>Chief Information Officer</fullName>
                </value>
                <value>
                    <fullName>PRA</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Executive Office</fullName>
                </value>
                <value>
                    <fullName>Legislative Office</fullName>
                </value>
                <value>
                    <fullName>Legal Office</fullName>
                </value>
                <value>
                    <fullName>Secretary</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BDO__c</fullName>
        <defaultValue>CASE($User.BDO__c, 
&quot;ARB&quot;, &quot;ARB&quot;, 
&quot;CalRecycle&quot;,&quot;CalRecycle&quot;, 
&quot;DTSC&quot;,&quot;DTSC&quot;, 
&quot;DPR&quot;,&quot;DPR&quot;, 
&quot;SWRCB&quot;,&quot;SWRCB&quot;, 
&quot;OEHHA&quot;,&quot;OEHHA&quot;,
&quot;Agency&quot;)</defaultValue>
        <label>Assigned BDO</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>ARB</fullName>
                </value>
                <value>
                    <fullName>CalRecycle</fullName>
                </value>
                <value>
                    <fullName>DPR</fullName>
                </value>
                <value>
                    <fullName>DTSC</fullName>
                </value>
                <value>
                    <fullName>OEHHA</fullName>
                </value>
                <value>
                    <fullName>SWRCB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAMS_Assignment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup for CAMS Assignment.</description>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>CAMS_Tasks2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>CAMS Task Due Date</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <formula>CAMS_Assignment__r.Subject__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subject</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>CAMS Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/CAMSFileUploadControllerTests.cls
@isTest
public class CAMSFileUploadControllerTests 
{
    /*
        SaveTheChunk
            blank file id
            not blank file id
    */
    static testMethod void SaveCAMSFileForAssignmentTest()
    {
        //Arrange
        boolean expected = true;
        Id controlledCorrespondenceRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'CAMS_Assignment__c' AND DeveloperName = 'Controlled_Correspondence'].Id;
        CAMS_Assignment__c assignment = new CAMS_Assignment__c();
        assignment.RecordTypeId = controlledCorrespondenceRecordTypeId;
        assignment.Subject__c = 'Lorem Ipsum';
        assignment.BDO__c = 'Agency';
        assignment.BDO_Suborganization__c = 'Executive Office'; 
        insert assignment;

        ContentVersion cv=new Contentversion();
        cv.title='ABC';
        cv.PathOnClient ='test';
        Blob b=Blob.valueOf('Unit Test Attachment Body');
        cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv;

        string title = 'Test File';
        string name = 'Test File Name';
        string description = 'Test File Description';
        string fin = 'false';
        //Act
        boolean actual = CAMSFileUploadController.SaveCAMSFile(assignment.Id, name, description, cv.Id, fin);
        
        //Assert
        System.assertEquals(expected, actual);
    }

    static testMethod void SaveCAMSFileForTaskTest()
    {
        //Arrange
        boolean expected = true;
        Id controlledCorrespondenceRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'CAMS_Assignment__c' AND DeveloperName = 'Controlled_Correspondence'].Id;
        CAMS_Assignment__c assignment = new CAMS_Assignment__c();
        assignment.RecordTypeId = controlledCorrespondenceRecordTypeId;
        assignment.Subject__c = 'Lorem Ipsum';
        assignment.BDO__c = 'Agency';
        assignment.BDO_Suborganization__c = 'Executive Office'; 
        insert assignment;

        CAMS_Task__c task = new CAMS_Task__c();
        task.BDO__c = 'Agency';
        task.BDO_Suborganization__c = 'Executive Office';
        task.CAMS_Assignment__c = assignment.Id;
        task.Due_Date__c = Date.Today().AddDays(3);
        insert task;

        ContentVersion cv=new Contentversion();
        cv.title='ABC';
        cv.PathOnClient ='test';
        Blob b=Blob.valueOf('Unit Test Attachment Body');
        cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv;

        string title = 'Test File';
        string name = 'Test File Name';
        string description = 'Test File Description';
        string fin = 'false';
        //Act
        boolean actual = CAMSFileUploadController.SaveCAMSFile(task.Id, name, description, cv.Id, fin);
        
        //Assert
        System.assertEquals(expected, actual);
    }

    static testMethod void SaveTheChunkBlankFileIdTest()
    {
        //Arrange
        Id controlledCorrespondenceRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'CAMS_Assignment__c' AND DeveloperName = 'Controlled_Correspondence'].Id;
        CAMS_Assignment__c assignment = new CAMS_Assignment__c();
        assignment.RecordTypeId = controlledCorrespondenceRecordTypeId;
        assignment.Subject__c = 'Lorem Ipsum';
        assignment.BDO__c = 'Agency';
        assignment.BDO_Suborganization__c = 'Executive Office'; 
        insert assignment;

        Id parentId = assignment.Id;
        string fileName ='ABC';
        string base64Data = 'Unit Test Attachment Body';
        string contentType = '';
        string fileId = '';
        //Act
        Id actual = CAMSFileUploadController.SaveTheChunk(parentId, fileName, base64Data, contentType, fileId);
        //Assert
        system.assertNotEquals(null, actual);

    }

    static testMethod void SaveTheChunkNotBlankFileIdTest()
    {
        //Arrange
        Id controlledCorrespondenceRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'CAMS_Assignment__c' AND DeveloperName = 'Controlled_Correspondence'].Id;
        CAMS_Assignment__c assignment = new CAMS_Assignment__c();
        assignment.RecordTypeId = controlledCorrespondenceRecordTypeId;
        assignment.Subject__c = 'Lorem Ipsum';
        assignment.BDO__c = 'Agency';
        assignment.BDO_Suborganization__c = 'Executive Office'; 
        insert assignment;

        ContentVersion cv=new Contentversion();
        cv.title='ABC';
        cv.PathOnClient ='test';
        Blob b=Blob.valueOf('Unit Test Attachment Body');
        cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv;

        Id parentId = assignment.Id;
        string fileName ='ABC';
        string base64Data = 'Unit Test Attachment Body';
        string contentType = '';
        string fileId = cv.Id;

        //Act
        Id actual = CAMSFileUploadController.SaveTheChunk(parentId, fileName, base64Data, contentType, fileId);
        
        //Assert
        system.assertNotEquals(null, actual);

    }
}