unpackaged/objects/CAMS_Assignment__c.object
<CustomObject>
    <description>Custom object for CAMS app. Creates a record for tracking correspondence....</description>
    <fields>
        <fullName>BDO_Suborganization__c</fullName>
        <label>Division, Office or Program</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BDO__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Climate Policy</fullName>
                </value>
                <value>
                    <fullName>Environmental Policy</fullName>
                </value>
                <value>
                    <fullName>Health and Public Policy</fullName>
                </value>
                <value>
                    <fullName>Legislative Affairs</fullName>
                </value>
                <value>
                    <fullName>Law Enforcement and Counsel</fullName>
                </value>
                <value>
                    <fullName>Environmental Justice and Tribal</fullName>
                </value>
                <value>
                    <fullName>Fiscal and Admin Programs</fullName>
                </value>
                <value>
                    <fullName>Unified Program</fullName>
                </value>
                <value>
                    <fullName>Chief Information Officer</fullName>
                </value>
                <value>
                    <fullName>PRA</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Executive Office</fullName>
                </value>
                <value>
                    <fullName>Legislative Office</fullName>
                </value>
                <value>
                    <fullName>Legal Office</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Secretary</fullName>
                    <isActive>false</isActive>
                    <label>Secretary</label>
                </value>
                <value>
                    <fullName>Undersecretary</fullName>
                    <isActive>false</isActive>
                    <label>Undersecretary</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BDO__c</fullName>
        <defaultValue>CASE($User.BDO__c, 
&quot;ARB&quot;, &quot;ARB&quot;,
&quot;CalRecycle&quot;,&quot;CalRecycle&quot;,
&quot;DTSC&quot;,&quot;DTSC&quot;,
&quot;DPR&quot;,&quot;DPR&quot;,
&quot;SWRCB&quot;,&quot;SWRCB&quot;,
&quot;OEHHA&quot;,&quot;OEHHA&quot;,
&quot;Agency&quot;)</defaultValue>
        <description>Defines the Department, Board or Office that initiated the assignment.</description>
        <label>BDO</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ARB</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>CalRecycle</fullName>
                </value>
                <value>
                    <fullName>DPR</fullName>
                </value>
                <value>
                    <fullName>DTSC</fullName>
                </value>
                <value>
                    <fullName>OEHHA</fullName>
                </value>
                <value>
                    <fullName>SWRCB</fullName>
                </value>
                <value>
                    <fullName>OOS</fullName>
                    <isActive>false</isActive>
                    <label>OOS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <defaultValue>TODAY() +14</defaultValue>
        <description>Date when correspondence is due back after review and sign</description>
        <label>Due Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of Correspondence</description>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>CAMS-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <recordTypes>
        <fullName>Controlled_Correspondence</fullName>
        <active>true</active>
        <label>4 Controlled Correspondence</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CAMS_Task__c.object
<CustomObject>
    <description>Task associated to CAMS Assignment.</description>
    <fields>
        <fullName>BDO_Suborganization__c</fullName>
        <label>Division, Office or Program</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BDO__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Undersecretary</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Climate Policy</fullName>
                </value>
                <value>
                    <fullName>Environmental Policy</fullName>
                </value>
                <value>
                    <fullName>Health and Public Policy</fullName>
                </value>
                <value>
                    <fullName>Legislative Affairs</fullName>
                </value>
                <value>
                    <fullName>Law Enforcement and Counsel</fullName>
                </value>
                <value>
                    <fullName>Environmental Justice and Tribal</fullName>
                </value>
                <value>
                    <fullName>Fiscal and Admin Programs</fullName>
                </value>
                <value>
                    <fullName>Unified Program</fullName>
                </value>
                <value>
                    <fullName>Chief Information Officer</fullName>
                </value>
                <value>
                    <fullName>PRA</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Executive Office</fullName>
                </value>
                <value>
                    <fullName>Legislative Office</fullName>
                </value>
                <value>
                    <fullName>Legal Office</fullName>
                </value>
                <value>
                    <fullName>Secretary</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BDO__c</fullName>
        <defaultValue>CASE($User.BDO__c, 
&quot;ARB&quot;, &quot;ARB&quot;, 
&quot;CalRecycle&quot;,&quot;CalRecycle&quot;, 
&quot;DTSC&quot;,&quot;DTSC&quot;, 
&quot;DPR&quot;,&quot;DPR&quot;, 
&quot;SWRCB&quot;,&quot;SWRCB&quot;, 
&quot;OEHHA&quot;,&quot;OEHHA&quot;,
&quot;Agency&quot;)</defaultValue>
        <label>Assigned BDO</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>ARB</fullName>
                </value>
                <value>
                    <fullName>CalRecycle</fullName>
                </value>
                <value>
                    <fullName>DPR</fullName>
                </value>
                <value>
                    <fullName>DTSC</fullName>
                </value>
                <value>
                    <fullName>OEHHA</fullName>
                </value>
                <value>
                    <fullName>SWRCB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAMS_Assignment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup for CAMS Assignment.</description>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>CAMS_Tasks2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>CAMS Task Due Date</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <formula>CAMS_Assignment__r.Subject__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subject</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>CAMS Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>BDO__c</fullName>
        <label>BDO</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ARB</fullName>
                </value>
                <value>
                    <fullName>CalRecycle</fullName>
                </value>
                <value>
                    <fullName>DTSC</fullName>
                </value>
                <value>
                    <fullName>DPR</fullName>
                </value>
                <value>
                    <fullName>SWRCB</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>OEHHA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/CAMSCreateSubtaskControllerTests.cls
@isTest
public class CAMSCreateSubtaskControllerTests 
{
   
    static testMethod void GetParentDueDateTest()
    {
        //Arrange
        Date expected = Date.Today().AddDays(3);
        Id controlledCorrespondenceRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'CAMS_Assignment__c' AND DeveloperName = 'Controlled_Correspondence'].Id;
        CAMS_Assignment__c assignment = new CAMS_Assignment__c();
        assignment.RecordTypeId = controlledCorrespondenceRecordTypeId;
        assignment.Subject__c = 'Lorem Ipsum';
        assignment.BDO__c = 'Agency';
        assignment.BDO_Suborganization__c = 'Executive Office'; 
        assignment.Due_Date__c = Date.Today().AddDays(14);
        insert assignment;
        
        CAMS_Task__c task = new CAMS_Task__c();
        task.BDO__c = 'Agency';
        task.BDO_Suborganization__c = 'Executive Office';
        task.CAMS_Assignment__c = assignment.Id;
        task.Due_Date__c = Date.Today().AddDays(3);
        insert task;


        //Act
        Date actual = CAMSCreateSubtaskController.GetParentDueDate(task.Id);

        //Assert
        System.assertEquals(expected, actual);
    }

    static testMethod void GetBDOsTest()
    {
        //Arrange
        integer expected = 1;
        integer actual = null;
        Id controlledCorrespondenceRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'CAMS_Assignment__c' AND DeveloperName = 'Controlled_Correspondence'].Id;
        CAMS_Assignment__c assignment = new CAMS_Assignment__c();
        assignment.RecordTypeId = controlledCorrespondenceRecordTypeId;
        assignment.Subject__c = 'Lorem Ipsum';
        assignment.BDO__c = 'Agency';
        assignment.BDO_Suborganization__c = 'Executive Office'; 
        assignment.Due_Date__c = Date.Today().AddDays(14);
        insert assignment;
        
        CAMS_Task__c task = new CAMS_Task__c();
        task.BDO__c = 'Agency';
        task.BDO_Suborganization__c = 'Executive Office';
        task.CAMS_Assignment__c = assignment.Id;
        task.Due_Date__c = Date.Today().AddDays(3);
        insert task;





        
        //Act
        actual = CAMSCreateSubtaskController.GetBDOs(task.Id).Size();
        

        //Assert
        System.assertEquals(expected, actual);
    }

    static testMethod void GetStatusesTest()
    {
        //Arrange
        integer expected = 7;

        //Act
        integer actual = CAMSCreateSubtaskController.GetStatuses().Size();
        
        //Assert
        System.assertEquals(expected, actual);
    }

    static testMethod void GetBDOSuborganizationsNotAgencyForAgencyTest()
    {
        //Arrange
        integer expected = 3;
        integer actual = null;
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='CAMS Agency Assigner Platform User'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
         UserName=uniqueUserName, BDO__c='ARB');

        
        //Act
        System.runAs(u) 
        {
            actual = CAMSCreateSubtaskController.GetBDOSuborganizations('Agency').Size();
        }
        

        //Assert
        System.assertEquals(expected, actual);
    }

    static testMethod void GetBDOSuborganizationsBDOForSameBDO()
    {
        //Arrange
        integer expected = 5;
        integer actual = null;
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='CAMS Agency Assigner Platform User'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
         UserName=uniqueUserName, BDO__c='ARB');

        
        //Act
        System.runAs(u) 
        {
            actual = CAMSCreateSubtaskController.GetBDOSuborganizations('ARB').Size();
        }
        

        //Assert
        System.assertEquals(expected, actual);
    }

    static testMethod void GetQueueUsersTest()
    {
        //Arrange
        integer expected = 3;
        Profile assignerProfile = [SELECT Id FROM Profile WHERE Name='CAMS BDO Assigner Platform User'];
        Profile reviewerProfile = [SELECT Id FROM Profile WHERE Name='CAMS BDO Reviewer Platform User'];

        Group testGroup = new Group(Name='Test Group', DeveloperName='Test_Group', Type='Regular');
        insert testGroup;

        Group testQueue = new Group(Name='Test Group', DeveloperName='Test_Group', Type='Queue');
        insert testQueue;

        String uniqueUserName1 = 'standarduser' + DateTime.now().getTime() + '1@testorg.com';
        User assigner = new User();
        assigner.Alias = 'standt'; 
        assigner.Email='standarduser@testorg.com';
        assigner.EmailEncodingKey='UTF-8'; 
        assigner.LastName='Testing'; 
        assigner.LanguageLocaleKey='en_US';
        assigner.LocaleSidKey='en_US'; 
        assigner.ProfileId = assignerProfile.Id;
        assigner.TimeZoneSidKey='America/Los_Angeles';
        assigner.UserName=uniqueUserName1;
        assigner.BDO__c='Agency';
        insert assigner;

        String uniqueUserName2 = 'standarduser' + DateTime.now().getTime() + '1@testorg.com';
        User reviewer = new User();
        reviewer.Alias = 'standt'; 
        reviewer.Email='standarduser@testorg.com';
        reviewer.EmailEncodingKey='UTF-8'; 
        reviewer.LastName='Testing'; 
        reviewer.LanguageLocaleKey='en_US';
        reviewer.LocaleSidKey='en_US'; 
        reviewer.ProfileId = reviewerProfile.Id;
        reviewer.TimeZoneSidKey='America/Los_Angeles';
        reviewer.UserName=uniqueUserName2;
        reviewer.BDO__c='Agency';
        insert reviewer;

        GroupMember gm1 = new GroupMember();
        gm1.UserOrGroupId = assigner.Id;
        gm1.GroupId = testQueue.Id;
        insert gm1;

        GroupMember gm2 = new GroupMember();
        gm2.UserOrGroupId = reviewer.Id;
        gm2.GroupId = testGroup.Id;
        insert gm2;

        //Act
        integer actual = CAMSCreateSubtaskController.GetQueueUsers('Test','Group').Size();
        
        //Assert
        System.assertEquals(expected, actual);
    }

    static testMethod void SaveChildTaskTest()
    {
        //Arrange
        string expected = 'Agency';
        string actual = null;
        
        
        Id controlledCorrespondenceRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'CAMS_Assignment__c' AND DeveloperName = 'Controlled_Correspondence'].Id;
        CAMS_Assignment__c assignment = new CAMS_Assignment__c();
        assignment.RecordTypeId = controlledCorrespondenceRecordTypeId;
        assignment.Subject__c = 'Lorem Ipsum';
        assignment.BDO__c = 'Agency';
        assignment.BDO_Suborganization__c = 'Executive Office'; 
        insert assignment;
        
        CAMS_Task__c task = new CAMS_Task__c();
        task.BDO__c = 'Agency';
        task.BDO_Suborganization__c = 'Executive Office';
        task.CAMS_Assignment__c = assignment.Id;
        task.Due_Date__c = date.Today().addDays(3);
        insert task;

        //Act
        string subTaskDueDate =  date.Today().addDays(2).format();
        CAMS_Task__c subtask = CAMSCreateSubtaskController.SaveChildTask(task.Id, 'Agency', 'Executive Office', null, subTaskDueDate, 'Pending', null);
        actual = subtask.BDO__c;
        
        //Assert
        System.assertEquals(expected, actual);
    }
}