unpackaged/objects/CAMS_Assignment__c.object
<CustomObject>
    <description>Custom object for CAMS app. Creates a record for tracking correspondence....</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Detailed notes and comments regarding the assignment ......Added by Susmita</description>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Pending&quot;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Back to BDO</fullName>
                    <isActive>false</isActive>
                    <label>Back to BDO</label>
                </value>
                <value>
                    <fullName>Delegated</fullName>
                    <isActive>false</isActive>
                    <label>Delegated</label>
                </value>
                <value>
                    <fullName>Governor&apos;s Office</fullName>
                    <isActive>false</isActive>
                    <label>Governor&apos;s Office</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>MID(RecordType.Name, 3, LEN(RecordType.Name)-2)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>CAMS-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CAMS_History__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assignment_Name__c</fullName>
        <label>Assignment Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>CAMS History</relationshipLabel>
        <relationshipName>CAMS_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name_Id__c</fullName>
        <label>Name Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Name__c</fullName>
        <label>Task Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
                <value>
                    <fullName>Note</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CAMS_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CAMS History</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>CAMS History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAMS History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/CAMS_Task__c.object
<CustomObject>
    <description>Task associated to CAMS Assignment.</description>
    <fields>
        <fullName>CAMS_Assignment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup for CAMS Assignment.</description>
        <label>Assignment</label>
        <referenceTo>CAMS_Assignment__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>CAMS_Tasks2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CAMS_Task__c.CAMS_Assignment__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.CAMS_Assignment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CAMS_Task__c</referenceTo>
        <relationshipLabel>Child Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Pending&quot;</defaultValue>
        <description>Status for CAMS Task</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Delegated</fullName>
                </value>
                <value>
                    <fullName>Governors Office</fullName>
                    <label>Governor&apos;s Office</label>
                </value>
                <value>
                    <fullName>Back to Requestor</fullName>
                </value>
                <value>
                    <fullName>Back to Assigned</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Back to BDO</fullName>
                    <isActive>false</isActive>
                    <label>Back to BDO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Concurrent</fullName>
                    <default>true</default>
                    <label>Concurrent</label>
                </value>
                <value>
                    <fullName>Sequential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>CAMS_Assignment__r.Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>CAMS Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <recordTypes>
        <fullName>Concurrent</fullName>
        <active>false</active>
        <label>Concurrent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sequential</fullName>
        <active>false</active>
        <label>Sequential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/CAMSTaskTriggerHandler.cls
public without sharing class CAMSTaskTriggerHandler extends TriggerHandler 
{
    //Dalden 04/30/2019:  This method is needed because it contains advanced validation
    protected override void beforeInsert()
    {
       
        for(CAMS_Task__c task: (List<CAMS_Task__c>)trigger.new)
        {
            if (task.task_type__c == 'Sequential') 
            {
                List<CAMS_Task__c> initialTasks = [SELECT Id, Status__c FROM CAMS_Task__c WHERE CAMS_Assignment__c =: task.CAMS_Assignment__c AND task_type__c = 'Concurrent'];
        
                if (initialTasks.size() == 0) 
                {
                    task.addError('The first task for an Assignment must be Concurrent'); 
                }
            }
            
            if (task.Related_To__c != null) 
            {
                CAMS_Task__c relatedToTask = [SELECT Id, Related_To__c FROM CAMS_Task__c WHERE Id =: task.Related_To__c];
                if (relatedToTask.Related_To__c != null) 
                {
                    task.addError('You cannot create a child task from a child task.'); 
                }   
            }
        }
    }
    
    //Dalden 04/11/2019:  The BeforeUpdate Method is fully refactored
    protected override void beforeUpdate()
    {    
        System.Debug('beforeUpdate');
        for(CAMS_Task__c task: (List<CAMS_Task__c>)trigger.new)
        {
            if (task.task_type__c == 'Sequential') 
            {
                List<CAMS_Task__c> initialTasks = [SELECT Id, Status__c FROM CAMS_Task__c WHERE CAMS_Assignment__c =: task.CAMS_Assignment__c AND task_type__c = 'Concurrent' AND Id <>: task.Id];
                if (initialTasks.size() == 0) 
                {
                    task.addError('The first task for an Assignment must be Concurrent'); 
                }
            }


            CAMS_Task__c oldTask = ((CAMS_Task__c)Trigger.oldMap.get(task.Id));
            if(oldTask.Status__c != Task.Status__c)
            {
                if(Task.Status__c == 'Completed')
                {
                    List<CAMS_Task__c> childTasks = [SELECT Id, CAMS_Assignment__c, Status__c FROM CAMS_Task__c WHERE Related_to__c = :task.Id AND status__c in ('Pending','Delegated','Governors Office','Back to Requestor','Back to Assigned')];
                    if (childTasks.size() > 0)
                    {
                        task.AddError('You must complete the Subtasks before completing this task.');
                    }
                    task.Completed_Date__c = date.today();
                }
                if(Task.Status__c <> 'Completed')
                {
                    task.Completed_Date__c = null;
                }
            }
        }
    }

    //Dalden 04/30/2019:  This method is needed because there are no other ways to handle deletes
    protected override void afterDelete()
    {  
        List<CAMS_History__c> histories = new List<CAMS_History__c>();
        for (CAMS_Task__c t : (List<CAMS_Task__c>)Trigger.old)
        {
            CAMS_History__c history = new CAMS_History__c();
            history.Action__c = 'Delete';
            history.Assignment__c = t.CAMS_Assignment__c;
            history.Assignment_Name__c = t.CAMS_Assignment__r.Name;
            history.Description__c = 'Deleted';
            history.Name_Id__c = t.Name;
            history.Task_Name__c = t.Name;
            history.Type__c = 'Task';
            history.User__c = UserInfo.getUserId();
            histories.Add(history);
        }
        insert histories;
    }
}