unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CERS_Resolution_Type__c</fullName>
        <label>Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Training/Advice Provided</fullName>
                </value>
                <value>
                    <fullName>Cancelled by user</fullName>
                </value>
                <value>
                    <fullName>Could not replicate</fullName>
                </value>
                <value>
                    <fullName>Duplicate record</fullName>
                </value>
                <value>
                    <fullName>No action taken</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Related Case Resolved</fullName>
                </value>
                <value>
                    <fullName>Entered as Change Request/Enhancement</fullName>
                </value>
                <value>
                    <fullName>Resolved by User</fullName>
                </value>
                <value>
                    <fullName>User Error</fullName>
                </value>
                <value>
                    <fullName>Workaround</fullName>
                </value>
                <value>
                    <fullName>Referred to Regulator</fullName>
                </value>
                <value>
                    <fullName>Correction Made</fullName>
                </value>
                <value>
                    <fullName>Complaint Entered</fullName>
                </value>
                <value>
                    <fullName>Access Granted</fullName>
                </value>
                <value>
                    <fullName>Associated with Complaint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Complaint_Message__c.object
<CustomObject>
    <fields>
        <fullName>CC_Addresses__c</fullName>
        <label>CC Addresses</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Complaint Messages</relationshipLabel>
        <relationshipName>Complaint_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EmailMessageId__c</fullName>
        <label>EmailMessageId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Email__c</fullName>
        <label>From Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>To_Addresses__c</fullName>
        <label>To Addresses</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Complaint Message</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Complaint Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ComplaintCaseEmailAssociationController.cls
public class ComplaintCaseEmailAssociationController 
{
	@AuraEnabled 
    public static void Associate(string caseId, string complaintId)	 
	{  
		try 
		{
            AssociateCaseAndComplaint(caseId,complaintId);
            
        }
		catch (DMLException de) 
		{
			String message = de.getDmlMessage(0);
			throw new AuraHandledException(message);    
		} 
		catch (Exception e) 
		{
			throw new AuraHandledException(e.getMessage());    
		}
    	finally 
		{
        	// Something executed whether there was an error or not
    	}       
    }  
    
    @AuraEnabled 
    public static void AssociateAndClose(string caseId, string complaintId)	 
	{  
		try 
		{
            AssociateCaseAndComplaint(caseId,complaintId);
            CloseCase(caseId);
        }
		catch (DMLException de) 
		{
			String message = de.getDmlMessage(0);
			throw new AuraHandledException(message);    
		} 
		catch (Exception e) 
		{
			throw new AuraHandledException(e.getMessage());    
		}
    	finally 
		{
        	// Something executed whether there was an error or not
    	}       
    }  
    
    private static void AssociateCaseAndComplaint(string caseId, string complaintId)	 
	{  
        List<Complaint_Message__c> newComplaintMessages = new List<Complaint_Message__c>();
		List<EmailMessage> messages = [SELECT Id,CcAddress,FromName,FromAddress,HtmlBody,Subject,ToAddress,ContentDocumentIds FROM EmailMessage WHERE ParentId=:caseId];
        List<Id> emailMessageIds = new List<Id>();
        for(EmailMessage message : messages)
        {
            emailMessageIds.Add(message.Id);
            Complaint_Message__c complaintMessage = new Complaint_Message__c();
            complaintMessage.CC_Addresses__c = message.CcAddress;
            complaintMessage.Complaint__c = complaintId;
            complaintMessage.From__c = message.FromName;
            complaintMessage.From_Email__c = message.FromAddress;
            complaintMessage.Message__c = message.HtmlBody;
            complaintMessage.Subject__c = message.Subject;
            complaintMessage.To_Addresses__c = message.ToAddress;
            complaintMessage.EmailMessageId__c = message.Id;
            //Attachments
            newComplaintMessages.Add(complaintMessage);
        }
        insert newComplaintMessages;
        List<Attachment> attachments = [SELECT Id, Name, Body, ContentType, ParentId,OwnerId FROM Attachment WHERE ParentId in: emailMessageIds];
        for(EmailMessage message : messages)
        {
            for(Attachment attach : attachments)
            {                
                if(attach.ParentId == message.Id)
                {
                 	//Insert ContentVersion
                    ContentVersion cVersion = new ContentVersion();
                    cVersion.ContentLocation = 'S'; //S-Document is in Salesforce. E-Document is outside of Salesforce. L-Document is on a Social Netork.
                    cVersion.PathOnClient = attach.Name;//File name with extention
                    cVersion.Origin = 'H';//C-Content Origin. H-Chatter Origin.
                    //cVersion.OwnerId = attach.OwnerId;//Owner of the file
                    cVersion.Title = attach.Name;//Name of the file
                    cVersion.VersionData = attach.Body;//File content
                    Insert cVersion;
                     
                    //After saved the Content Verison, get the ContentDocumentId
                    Id conDocument = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cVersion.Id].ContentDocumentId;
                    for(Complaint_Message__c cm : newComplaintMessages)
        			{
                        if(cm.EmailMessageId__c==message.Id)
                        {
                            ContentDocumentLink cDocLink1 = new ContentDocumentLink();
                            cDocLink1.ContentDocumentId = conDocument;//Add ContentDocumentId
                            cDocLink1.LinkedEntityId = cm.Id;//Add attachment parentId
                            cDocLink1.ShareType = 'I';//V - Viewer permission. C - Collaborator permission. I - Inferred permission.
                            cDocLink1.Visibility = 'InternalUsers';//AllUsers, InternalUsers, SharedUsers
                            Insert cDocLink1;
                            
                            ContentDocumentLink cDocLink2 = new ContentDocumentLink();
                            cDocLink2.ContentDocumentId = conDocument;//Add ContentDocumentId
                            cDocLink2.LinkedEntityId = cm.Complaint__c;//Add attachment parentId
                            cDocLink2.ShareType = 'I';//V - Viewer permission. C - Collaborator permission. I - Inferred permission.
                            cDocLink2.Visibility = 'InternalUsers';//AllUsers, InternalUsers, SharedUsers
                            Insert cDocLink2;
                        }
                    }
                }
            }
        }
    }  
    
    private static void CloseCase(string caseId)	 
	{  
		Case c = [SELECT Id, Status FROM Case WHERE Id=:caseId];
        c.Status='Closed';
        c.CERS_Resolution_Type__c = 'Associated with Complaint';
        update c;
    }  
}