unpackaged/objects/Complaints__c.object
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Finding__c.object
<CustomObject>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Violations_or_Compliance_Issues__c</fullName>
        <description>Did you find violations or compliance issues?</description>
        <inlineHelpText>Did you find violations or compliance issues?</inlineHelpText>
        <label>Violations or Compliance Issues</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <label>Finding</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Finding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/DashboardCompsWithEnforcementController.cls
public class DashboardCompsWithEnforcementController 
{
    @AuraEnabled 
    public static string GetComplaintsWithEnforcementAction() 
	{
        List<Finding__c> findings = [SELECT Id, Complaint__c, Complaint__r.Name, CreatedDate FROM Finding__c WHERE Violations_or_Compliance_Issues__c = 'Yes' ORDER BY CreatedDate desc];
        List<DashboardCompsWithEnforcementWrapper> l = new List<DashboardCompsWithEnforcementWrapper>();
        for(Finding__c finding : findings)
        {
            DashboardCompsWithEnforcementWrapper d = new DashboardCompsWithEnforcementWrapper();
            d.Id = finding.Id;
            d.URL = URL.getSalesforceBaseUrl().toExternalForm() + '/' + d.Id;
            d.ComplaintNumber = finding.Complaint__r.Name;
            d.CreatedDate = finding.CreatedDate.format('MM/dd/yyyy');
            l.add(d);
        }
        return System.json.serialize(l);
    }

    class DashboardCompsWithEnforcementWrapper
    {
       @AuraEnabled
       public String Id;
       @AuraEnabled
       public String URL;
       @AuraEnabled
       public String ComplaintNumber;
       @AuraEnabled
       public string CreatedDate;
    }

}