unpackaged/objects/Complaints__c.object
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Finding__c.object
<CustomObject>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Finding</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Referral__c</fullName>
        <description>Date Referred to to External Agency</description>
        <inlineHelpText>Date Referred to to External Agency</inlineHelpText>
        <label>Date of Referral</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Site_Visit__c</fullName>
        <description>Date of Site Visit</description>
        <inlineHelpText>Date of Site Visit</inlineHelpText>
        <label>Date of Site Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Enforcement_Complete__c</fullName>
        <description>Is Enforcement Complete?</description>
        <inlineHelpText>Is Enforcement Complete?</inlineHelpText>
        <label>Is Enforcement Complete</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Going_Enforcement__c</fullName>
        <description>Describe any on-going enforcement efforts</description>
        <inlineHelpText>Describe any on-going enforcement efforts</inlineHelpText>
        <label>On-Going Enforcement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Reason_for_No_Site_Visit__c</fullName>
        <description>If other was selected for reason no site visit was conducted, please provide the reason here.</description>
        <inlineHelpText>If other was selected for reason no site visit was conducted, please provide the reason here.</inlineHelpText>
        <label>Other Reason for No Site Visit</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reason_for_No_Site_Visit__c</fullName>
        <description>If no site visit was conducted, why not?</description>
        <inlineHelpText>If no site visit was conducted, why not?</inlineHelpText>
        <label>Why didn&apos;t you conduct a site visit?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complaint is outside agency jurisdiction</fullName>
                </value>
                <value>
                    <fullName>Complaint lacked sufficient information</fullName>
                </value>
                <value>
                    <fullName>Complaint was referred to another agency for handling</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral_Agency__c</fullName>
        <description>Name of the Agency to which You Referred the Finding</description>
        <inlineHelpText>Name of the Agency to which You Referred the Finding</inlineHelpText>
        <label>Who Did You Refer it to?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Referral__c</fullName>
        <inlineHelpText>Did you refer this complaint to another agency?</inlineHelpText>
        <label>Did you refer this to another agency?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Visit_Conducted__c</fullName>
        <description>Did you conduct a site visit to investigate the complaint?</description>
        <inlineHelpText>Did you conduct a site visit to investigate the complaint?</inlineHelpText>
        <label>Did you conduct a site visit?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary_of_Violations_and_enforcement__c</fullName>
        <description>Summary of violations and enforcement action taken.</description>
        <inlineHelpText>Summary of violations and enforcement action taken.</inlineHelpText>
        <label>Summary of Violations and enforcement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Violations_Related_to_Complaint__c</fullName>
        <description>Were the violations related to the complaint?</description>
        <inlineHelpText>Were the violations related to the complaint?</inlineHelpText>
        <label>Violations Related to Complaint</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violations_or_Compliance_Issues__c</fullName>
        <description>Did you find violations or compliance issues?</description>
        <inlineHelpText>Did you find violations or compliance issues?</inlineHelpText>
        <label>Violations or Compliance Issues</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <label>Finding</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Finding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{00000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/FindingControllerTests.cls
@isTest
public class FindingControllerTests 
{
	

	public FindingControllerTests() 
	{
		
	}
 
	@isTest 
	static void TestLoadSFDCCreateNewFinding()
	{
		//Arrange
		string fakeComplaintId = UnitTestHelper.GetFakeId(Complaints__c.SObjectType);
		id idval = fakeComplaintId;
		fakeComplaintId = idval;                  
		ApexPages.currentPage().getParameters().put('lkid', fakeComplaintId); 
		PageReference expectedPageReference = null;
		Finding__c finding = new Finding__c();
		ApexPages.StandardController standardController = new ApexPages.StandardController(finding);
		FindingController controller = new FindingController(standardController);
		string expectedFindingComplaintId = fakeComplaintId;

		//Act
		PageReference actualPageReference = controller.LoadSFDCCreateNewFinding();
		string actualFindingComplaintId = controller.SFDCCreateNewFindingViewModel.Finding.Complaint__c;
		
		//Assert
		PageReferenceTestHelper.Assert(expectedPageReference, actualPageReference);
		System.AssertEquals(expectedFindingComplaintId, actualFindingComplaintId);

	}	

	@isTest static void TestSFDCCancelNewFinding()
	{
		//Arrange
		Account testAccount = UnitTestHelper.CreateTestAccount();
		Contact testContact = UnitTestHelper.CreateTestCalEPAPartnerContact(testAccount.Id, 'TestContact@TestAccount.edu');
		Complaints__c testComplaint = UnitTestHelper.CreateTestComplaint();
		Referral__c testReferral = UnitTestHelper.CreateTestReferral(testComplaint.Id, testAccount.Id,'');
		Finding__c testFinding = UnitTestHelper.CreateTestFinding(testComplaint.Id, testReferral.Id, testContact.Id);
		PageReference expected = new PageReference('/' + testComplaint.Id);
		expected.setRedirect(true);
		Finding__c finding = new Finding__c();
		ApexPages.StandardController standardController = new ApexPages.StandardController(finding);
		FindingController controller = new FindingController(standardController);
		controller.SFDCCreateNewFindingViewModel = new FindingController.SFDCCreateNewFindingViewModel();
		controller.SFDCCreateNewFindingViewModel.Finding = testFinding;

		//Act
		PageReference actual = controller.SFDCCancelNewFinding(); 
		
		//Assert
		PageReferenceTestHelper.Assert(expected, actual);

	}

	@isTest static void TestSFDCSaveNewFinding()
	{
		//Arrange
		Account testAccount = UnitTestHelper.CreateTestAccount();
		Contact testContact = UnitTestHelper.CreateTestCalEPAPartnerContact(testAccount.Id, 'TestContact@TestAccount.edu');
		Complaints__c testComplaint = UnitTestHelper.CreateTestComplaint();
		Referral__c testReferral = UnitTestHelper.CreateTestReferral(testComplaint.Id, testAccount.Id,'');
		Finding__c testFinding = new Finding__c();
		testFinding.Complaint__c = testComplaint.Id;
		testFinding.Contact__c = testContact.Id;
		testFinding.Date_of_Referral__c = Date.valueOf('2017-01-01 00:00:00');
		testFinding.Date_of_Site_Visit__c = Date.valueOf('2017-01-01 00:00:00');		
		testFinding.Is_Enforcement_Complete__c = 'Yes';
		testFinding.On_Going_Enforcement__c = '';
		testFinding.Other_Reason_for_No_Site_Visit__c = '';
		testFinding.Reason_for_No_Site_Visit__c = '';
		testFinding.Referral_Agency__c = 'Lorem Ipsum';
		testFinding.Referral__c = testReferral.Id;
		testFinding.Secondary_Referral__c = 'Yes';
		testFinding.Site_Visit_Conducted__c = 'Yes';
		testFinding.Summary_of_Violations_and_enforcement__c = 'Lorem Ipsum';
		testFinding.Violations_or_Compliance_Issues__c = 'No';
		testFinding.Violations_Related_to_Complaint__c = null;
		PageReference expectedPageReference = new PageReference('/' + testComplaint.Id);
		expectedPageReference.setRedirect(true);
		Finding__c finding = new Finding__c();
		ApexPages.StandardController standardController = new ApexPages.StandardController(finding);
		FindingController controller = new FindingController(standardController);
		controller.SFDCCreateNewFindingViewModel = new FindingController.SFDCCreateNewFindingViewModel();
		controller.SFDCCreateNewFindingViewModel.Finding = testFinding;
		string expectedComplaintId = testComplaint.Id;
		string expectedContactId = testContact.Id;
		Date expectedDateOfReferral = Date.valueOf('2017-01-01 00:00:00');
		Date expectedDateOfSiteVisit = Date.valueOf('2017-01-01 00:00:00');		
		string expectedIsEnforcementComplete = 'Yes';
		string expectedOnGoingEnforcement = '';
		string expectedOtherReasonForNoSiteVisit = '';
		string expectedReasonForNoSiteVisit = '';
		string expectedReferralAgency = 'Lorem Ipsum';
		string expectedReferralId = testReferral.Id;
		string expectedSecondaryReferral = 'Yes';
		string expectedSiteVisitConducted = 'Yes';
		string expectedSummaryOfViolationsAndEnforcement = 'Lorem Ipsum';
		string expectedViolationsOrComplianceIssues = 'No';
		string expectedViolationsRelatedToComplaint = null;
		//Act
		PageReference actualPageReference = controller.SFDCSaveNewFinding(); 
		string actualComplaintId = controller.SFDCCreateNewFindingViewModel.Finding.Complaint__c;
		string actualContactId = controller.SFDCCreateNewFindingViewModel.Finding.Contact__c;
		Date actualDateOfReferral = controller.SFDCCreateNewFindingViewModel.Finding.Date_of_Referral__c;
		Date actualDateOfSiteVisit = controller.SFDCCreateNewFindingViewModel.Finding.Date_of_Site_Visit__c;
		string actualIsEnforcementComplete = controller.SFDCCreateNewFindingViewModel.Finding.Is_Enforcement_Complete__c;
		string actualOnGoingEnforcement = controller.SFDCCreateNewFindingViewModel.Finding.On_Going_Enforcement__c;
		string actualOtherReasonForNoSiteVisit = controller.SFDCCreateNewFindingViewModel.Finding.Other_Reason_for_No_Site_Visit__c;
		string actualReasonForNoSiteVisit = controller.SFDCCreateNewFindingViewModel.Finding.Reason_for_No_Site_Visit__c;
		string actualReferralAgency = controller.SFDCCreateNewFindingViewModel.Finding.Referral_Agency__c;
		string actualReferralId = controller.SFDCCreateNewFindingViewModel.Finding.Referral__c;
		string actualSecondaryReferral = controller.SFDCCreateNewFindingViewModel.Finding.Secondary_Referral__c;
		string actualSiteVisitConducted = controller.SFDCCreateNewFindingViewModel.Finding.Site_Visit_Conducted__c;
		string actualSummaryOfViolationsAndEnforcement = controller.SFDCCreateNewFindingViewModel.Finding.Summary_of_Violations_and_enforcement__c;
		string actualViolationsOrComplianceIssues = controller.SFDCCreateNewFindingViewModel.Finding.Violations_or_Compliance_Issues__c;
		string actualViolationsRelatedToComplaint = controller.SFDCCreateNewFindingViewModel.Finding.Violations_Related_to_Complaint__c;
		
		//Assert
		PageReferenceTestHelper.Assert(expectedPageReference, actualPageReference);
		System.AssertEquals(expectedComplaintId, actualComplaintId);
		System.AssertEquals(expectedContactId, actualContactId);
		System.AssertEquals(expectedDateOfReferral, actualDateOfReferral);
		System.AssertEquals(expectedDateOfSiteVisit, actualDateOfSiteVisit);
		System.AssertEquals(expectedIsEnforcementComplete, actualIsEnforcementComplete);
		System.AssertEquals(expectedOnGoingEnforcement, actualOnGoingEnforcement);
		System.AssertEquals(expectedOtherReasonForNoSiteVisit, actualOtherReasonForNoSiteVisit);
		System.AssertEquals(expectedReasonForNoSiteVisit, actualReasonForNoSiteVisit);
		System.AssertEquals(expectedReferralAgency, actualReferralAgency);
		System.AssertEquals(expectedReferralId, actualReferralId);
		System.AssertEquals(expectedSecondaryReferral, actualSecondaryReferral);
		System.AssertEquals(expectedSiteVisitConducted, actualSiteVisitConducted);
		System.AssertEquals(expectedSummaryOfViolationsAndEnforcement, actualSummaryOfViolationsAndEnforcement);
		System.AssertEquals(expectedViolationsOrComplianceIssues, actualViolationsOrComplianceIssues);
		System.AssertEquals(expectedViolationsRelatedToComplaint, actualViolationsRelatedToComplaint);

	}
	
	
}