unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Open&quot;</defaultValue>
        <inlineHelpText>Under Review: Initial investigation is in progress or trying to Refer
Transferred:  Complaint has been assigned internally
Referred:  Complaint has been assigned and confirmed to an external partner
Closed/Actions Taken:  Closed for Cal EPA</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Finding__c.object
<CustomObject>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Finding</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Finding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Findings Received</fullName>
                </value>
                <value>
                    <fullName>Awaiting Findings</fullName>
                    <default>true</default>
                    <label>Awaiting Findings</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{00000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/FindingsTriggerTests.cls
@isTest
private class FindingsTriggerTests
{
    @isTest
    static void TestCreateNewFindingWithReferral()
    {
        //Arrange
        string expected = 'Findings Received';
        //Create an External Partner Account
        Account testAccount = UnitTestHelper.CreateTestAccount();
        //Create an External Partner Contact
        Contact testContact = UnitTestHelper.CreateTestCalEPAPartnerContact(testAccount.Id, 'TestContact@TestAccount.edu');
        //Create a Complaint
        Complaints__c testComplaint = UnitTestHelper.CreateTestComplaint();
        //Create a Referral
        Referral__c testReferral = UnitTestHelper.CreateTestReferral(testComplaint.Id, testAccount.Id,'');
        //Create a Finding

        //Act
        Test.startTest();
        Finding__c testFinding = UnitTestHelper.CreateTestFinding(testComplaint.Id, testReferral.Id, testContact.Id);
        Test.stopTest();
        Referral__c actualReferral = [SELECT Id, Status__c FROM Referral__c WHERE Id =: testReferral.Id];
        string actual = actualReferral.Status__c;

        //Assert
        System.AssertEquals(expected, actual);
    }
    
    @isTest
    static void TestUpdateFindingWithReferral()
    {
    //Arrange
        string expected = 'Findings Received';
        //Create an External Partner Account
        Account testAccount = UnitTestHelper.CreateTestAccount();
        //Create an External Partner Contact
        Contact testContact = UnitTestHelper.CreateTestCalEPAPartnerContact(testAccount.Id, 'TestContact@TestAccount.edu');
        //Create a Complaint
        Complaints__c testComplaint = UnitTestHelper.CreateTestComplaint();
        //Create a Referral
        Referral__c testReferral = UnitTestHelper.CreateTestReferral(testComplaint.Id, testAccount.Id,'');
        //Create a Finding

        //Act
        Finding__c testFinding = UnitTestHelper.CreateTestFinding(testComplaint.Id, null, testContact.Id);
        testFinding.Referral__c = testReferral.Id;
        Test.startTest();
        update testFinding;
        Test.stopTest();

        Referral__c actualReferral = [SELECT Id, Status__c FROM Referral__c WHERE Id =: testReferral.Id];
        string actual = actualReferral.Status__c;

        //Assert
        System.AssertEquals(expected, actual);
    }
    
}