unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Open&quot;</defaultValue>
        <inlineHelpText>Under Review: Initial investigation is in progress or trying to Refer
Transferred:  Complaint has been assigned internally
Referred:  Complaint has been assigned and confirmed to an external partner
Closed/Actions Taken:  Closed for Cal EPA</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>External Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SelectedContacts__c</fullName>
        <label>SelectedContacts</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Findings Received</fullName>
                </value>
                <value>
                    <fullName>Awaiting Findings</fullName>
                    <default>true</default>
                    <label>Awaiting Findings</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{00000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ReferralController.cls
public with sharing class ReferralController 
{
    public CreateReferralViewModel CreateReferralViewModel {get; set;}  
    public ReferralController(ApexPages.StandardController controller)
    {
        
    }
    //SFDC Create VisualForce Page

    public PageReference LoadCreateReferral()
    {
        CreateReferralViewModel = new CreateReferralViewModel();
        Map<String, String> params = ApexPages.currentPage().getParameters();
        system.debug('params:  ' + params);
        string complaintId = '';
        for(string paramId: params.KeySet())
        {
            if(paramId.Contains('lkid'))
            {
                complaintId = params.Get(paramId);
                break;
            }
        }
        if(complaintId != null)
        {
            CreateReferralViewModel.Referral.Complaint__c = complaintId;            
        }
        return null;
    }

    public List<Contact> GetContacts()
    {
        List<Contact> contacts = new List<Contact>();
        if(CreateReferralViewModel.Referral.External_Partner__c != null)
        {
            List<Contact> retrievedContacts = [SELECT Id, FirstName, LastName, Name, Email, Title FROM Contact Where Email != null AND Inactive__c = false and Id in (SELECT ContactId FROM AccountContactRelation WHERE AccountId =: CreateReferralViewModel.Referral.External_Partner__c )];
            for(Contact c : retrievedContacts)
            {
                contacts.add(c);
            }
        }
        return contacts;        
    }
    
    public PageReference Save()
    {
        if(CreateReferralViewModel.SelectedContacts == null || CreateReferralViewModel.SelectedContacts == '')
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'You must select at least one contact'));
            return null;
        }
        PageReference pr = new PageReference('/' + CreateReferralViewModel.Referral.Complaint__c);
        try
        {
            Create();
        }
        catch(System.DmlException e) 
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getDmlMessage(0)));
            return null;
        }
        return pr;
    }  
    
    public PageReference SaveAndNew()
    {
        if(CreateReferralViewModel.SelectedContacts == null ||CreateReferralViewModel.SelectedContacts == '')
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'You must select at least one contact'));
            return null;
        }
        PageReference pr = new PageReference('/apex/newReferral?complaint=' + CreateReferralViewModel.Referral.Complaint__c);
        try
        {
            Create();
        }
        catch(System.DmlException e) 
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getDmlMessage(0)));
               return null;
        }
        return pr; 
    }
    
    public PageReference Cancel()
    {
        PageReference pr = new PageReference('/' + CreateReferralViewModel.Referral.Complaint__c);
        pr.setRedirect(true);
        return pr;
    }

    private void Create()
    {
        //Create Referral or Retrieve Existing Referral
        List<Referral__c> existingReferrals = [SELECT Id, Complaint__c, External_Partner__c,Message__c,SelectedContacts__c   FROM Referral__c WHERE Complaint__c =: CreateReferralViewModel.Referral.Complaint__c AND External_Partner__c =: CreateReferralViewModel.Referral.External_Partner__c  ];
        if(existingReferrals.size() > 0)    
        {
            CreateReferralViewModel.Referral = existingReferrals[0];
            CreateReferralViewModel.Referral.Message__c = CreateReferralViewModel.Message;
            CreateReferralViewModel.Referral.SelectedContacts__c = CreateReferralViewModel.SelectedContacts;
            System.Debug('CreateReferralViewModel.Referral.SelectedContacts__c:  ' + CreateReferralViewModel.Referral.SelectedContacts__c);
            update CreateReferralViewModel.Referral; 
        }
        else
        {
            CreateReferralViewModel.Referral.Message__c = CreateReferralViewModel.Message;
            CreateReferralViewModel.Referral.SelectedContacts__c = CreateReferralViewModel.SelectedContacts;
            insert CreateReferralViewModel.Referral; 
        }
        //End Create Referral or Retrieve Existing Referral       
        
        //Update Complaint Status
        Complaints__c complaint = [SELECT Id, Name, Status__c from Complaints__c Where Id =: CreateReferralViewModel.Referral.Complaint__c];
        complaint.Status__c = 'Referred';
        update complaint;
        //End Update Complaint Status
    }
    
    //End SFDC Create VisualForce Page    

    public with sharing class CreateReferralViewModel 
    { 
        public string Message {get;set;}
        public Referral__c Referral { get; set; }
        public string SelectedContacts {get; set;} 
        
        public CreateReferralViewModel() 
        {
            Referral = new Referral__c();
        }
    }
    
    //MakeReferralsTestable
}