unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>BDO_For_Report__c</fullName>
        <formula>if( Number_of_BDOs__c   &gt; 1, &apos;Multi-BDO&apos;
, if( Air__c ,&apos;Air&apos;
     , if( Solid_Waste__c , &apos;Solid Waste&apos;
          , if( Pesticides__c , &apos;Pesticides&apos;
               , if( Toxic_Substances__c ,&apos;Toxic Substances&apos;
                    ,if( Water__c ,&apos;Water&apos;,&apos;&apos;
                     )
                  )
             )
        )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BDO For Report</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_Open__c</fullName>
        <formula>IF(TEXT(Status__c) = &quot;Closed/Actions Taken&quot;, ROUND(Closed_Date__c - DATEVALUE(Actual_Receive_Date__c),0), ROUND(TODAY() - DATEVALUE(Actual_Receive_Date__c),0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/DashboardAvgDaysOpenController.cls
public class DashboardAvgDaysOpenController 
{
    @AuraEnabled 
    public static long GetMaximumDaysOpen(string bdo) 
	{
        try 
		{
            if(bdo != 'All')
            {
                List<AggregateResult> result1 = [SELECT MAX(Days_Open__c)  FROM Complaints__c WHERE BDO_For_Report__c =: bdo];
                if(result1[0].get('expr0')==null)
                {
                    return 0;
                }
                string allStr = string.ValueOf(result1[0].get('expr0'));
                return long.valueOf(allStr);

            }
            else 
            {
                List<AggregateResult> result2 = [SELECT MAX(Days_Open__c)  FROM Complaints__c];
                if(result2[0].get('expr0')==null)
                {
                    return 0;
                }
                string bdoStr = string.ValueOf(result2[0].get('expr0'));
                return long.valueOf(bdoStr);
            } 
        }
		catch (Exception e) 
		{
			System.Debug('e:  ' + e);
			throw new AuraHandledException(e.getMessage());    
		}               
	}

    @AuraEnabled 
    public static long GetAverageDaysOpen(string bdo) 
	{
        try 
		{
            if(bdo != 'All')
            {
                List<AggregateResult> result1 = [SELECT AVG(Days_Open__c)  FROM Complaints__c WHERE BDO_For_Report__c =: bdo];
                if(result1[0].get('expr0')==null)
                {
                    return 0;
                }
                string allStr = string.ValueOf(result1[0].get('expr0'));
                decimal d = decimal.valueOf(allStr);
                return d.Round();

            }
            else 
            {
                List<AggregateResult> result2 = [SELECT AVG(Days_Open__c)  FROM Complaints__c];
                if(result2[0].get('expr0')==null)
                {
                    return 0;
                }
                string bdoStr = string.ValueOf(result2[0].get('expr0'));
                decimal d = decimal.valueOf(bdoStr);
                return d.Round();
            }     
        }
		catch (Exception e) 
		{
			System.Debug('e:  ' + e);
			throw new AuraHandledException(e.getMessage());    
		}               
	}
}