unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>BDO_For_Report__c</fullName>
        <formula>if( Number_of_BDOs__c   &gt; 1, &apos;Multi-BDO&apos;
, if( Air__c ,&apos;Air&apos;
     , if( Solid_Waste__c , &apos;Solid Waste&apos;
          , if( Pesticides__c , &apos;Pesticides&apos;
               , if( Toxic_Substances__c ,&apos;Toxic Substances&apos;
                    ,if( Water__c ,&apos;Water&apos;,&apos;&apos;
                     )
                  )
             )
        )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BDO For Report</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closed_Date__c</fullName>
        <description>Populated via workflow when the child complaint&apos;s status is changed to closed. JMC 2-15-2016</description>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Referred__c</fullName>
        <label>Date Referred</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_of_Quarter__c</fullName>
        <formula>IF
        (
        OR
        (
        MONTH(DATEVALUE(CreatedDate))=1,
        MONTH(DATEVALUE(CreatedDate))=2,
        MONTH(DATEVALUE(CreatedDate))=3
        ),
        DATE(YEAR(DATEVALUE(CreatedDate)),3,31),
        IF
        (
        OR
        (
        MONTH(DATEVALUE(CreatedDate))=4,
        MONTH(DATEVALUE(CreatedDate))=5,
        MONTH(DATEVALUE(CreatedDate))=6
        ),
        DATE(YEAR(DATEVALUE(CreatedDate)),6,30),


        IF
        (
        OR
        (
        MONTH(DATEVALUE(CreatedDate))=7,
        MONTH(DATEVALUE(CreatedDate))=8,
        MONTH(DATEVALUE(CreatedDate))=9
        ),
        DATE(YEAR(DATEVALUE(CreatedDate)),9,30),
        DATE(YEAR(DATEVALUE(CreatedDate)),12,31)
        )
        )
        )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End of Quarter</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_of_Year__c</fullName>
        <formula>DATE( YEAR( DATEVALUE( CreatedDate ) ) ,12,31)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End of Year</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Complaint_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Complaint ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Open&quot;</defaultValue>
        <inlineHelpText>Under Review: Initial investigation is in progress or trying to Refer
Transferred:  Complaint has been assigned internally
Referred:  Complaint has been assigned and confirmed to an external partner
Closed/Actions Taken:  Closed for Cal EPA</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Finding__c.object
<CustomObject>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Violations_or_Compliance_Issues__c</fullName>
        <description>Did you find violations or compliance issues?</description>
        <inlineHelpText>Did you find violations or compliance issues?</inlineHelpText>
        <label>Violations or Compliance Issues</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <label>Finding</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Finding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ExecutiveDashboardStatisticsController.cls
public class ExecutiveDashboardStatisticsController 
{
    @AuraEnabled 
    public static integer GetTotalComplaints(string bdo, DateTime beginDate, DateTime endDate) 
	{
        try 
		{
            List<Complaints__c> complaints = new List<Complaints__c>();
            
            
            if(bdo == 'All')
            {
                complaints = [SELECT Id FROM Complaints__c WHERE Original_Complaint_ID__c = null AND CreatedDate >=: beginDate AND CreatedDate <=: endDate ];
            }
            else 
            {
                complaints = [SELECT Id FROM Complaints__c WHERE Original_Complaint_ID__c = null AND BDO_For_Report__c =: bdo AND CreatedDate >=: beginDate AND CreatedDate <=: endDate];
            }                
            return complaints.Size();
        }
        catch (Exception e) 
		{
			System.Debug('e:  ' + e);
			throw new AuraHandledException(e.getMessage());    
		}
	}
    
     @AuraEnabled 
    public static integer GetTotalEnforcementActions(string bdo, DateTime beginDate, DateTime endDate) 
	{
        try 
		{
            List<Finding__c> findings = new List<Finding__c>();        
            if(bdo == 'All')
            {
                findings = [SELECT Id FROM Finding__c WHERE Complaint__r.Original_Complaint_ID__c = null AND Complaint__r.CreatedDate >=: beginDate AND Complaint__r.CreatedDate <=: endDate AND Violations_or_Compliance_Issues__c = 'Yes' ];
                //findings = [SELECT Id FROM Finding__c WHERE Complaint__r.Original_Complaint_ID__c = null AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Violations_or_Compliance_Issues__c = 'Yes'];
            }
            else 
            {
                findings = [SELECT Id FROM Finding__c WHERE Complaint__r.Original_Complaint_ID__c = null AND Complaint__r.BDO_For_Report__c =: bdo AND Complaint__r.CreatedDate >=: beginDate AND Complaint__r.CreatedDate <=: endDate AND Violations_or_Compliance_Issues__c = 'Yes'];
                //findings = [SELECT Id FROM Finding__c WHERE Complaint__r.Original_Complaint_ID__c = null AND Complaint__r.BDO_For_Report__c =: bdo AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Violations_or_Compliance_Issues__c = 'Yes'];
            }                
            return findings.Size();
        }
        catch (Exception e) 
		{
			System.Debug('e:  ' + e);
			throw new AuraHandledException(e.getMessage());    
		}
    }

    @AuraEnabled 
    public static integer GetReferredComplaints(string bdo, DateTime beginDate, DateTime endDate) 
	{
        try 
		{
            List<Complaints__c> complaints = new List<Complaints__c>();
            
            
            if(bdo == 'All')
            {
                complaints = [SELECT Id FROM Complaints__c WHERE Original_Complaint_ID__c = null AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Date_Referred__c <> null ];
            }
            else 
            {
                complaints = [SELECT Id FROM Complaints__c WHERE Original_Complaint_ID__c = null AND BDO_For_Report__c =: bdo AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Date_Referred__c <> null];
            }                
            return complaints.Size();
        }
        catch (Exception e) 
		{
			System.Debug('e:  ' + e);
			throw new AuraHandledException(e.getMessage());    
		}
	}

    @AuraEnabled 
    public static integer GetCalEPAOpenComplaints(string bdo, DateTime beginDate, DateTime endDate) 
	{
        try 
		{
            List<Complaints__c> complaints = new List<Complaints__c>();
            
            
            if(bdo == 'All')
            {
                complaints = [SELECT Id FROM Complaints__c WHERE Original_Complaint_ID__c = null AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Date_Referred__c = null AND Status__c <> 'Closed'];
            }
            else 
            {
                complaints = [SELECT Id FROM Complaints__c WHERE Original_Complaint_ID__c = null AND BDO_For_Report__c =: bdo AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Date_Referred__c = null AND Status__c <> 'Closed' ];
            }                
            return complaints.Size();
        }
        catch (Exception e) 
		{
			System.Debug('e:  ' + e);
			throw new AuraHandledException(e.getMessage());    
		}
	}
    
    @AuraEnabled 
    public static integer GetCalEPAClosedComplaints(string bdo, DateTime beginDate, DateTime endDate) 
	{
        try 
		{
            List<Complaints__c> complaints = new List<Complaints__c>();
            
            
            if(bdo == 'All')
            {
                complaints = [SELECT Id FROM Complaints__c WHERE Original_Complaint_ID__c = null AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Date_Referred__c = null AND Status__c='Closed' ];
            }
            else 
            {
                complaints = [SELECT Id FROM Complaints__c WHERE Original_Complaint_ID__c = null AND BDO_For_Report__c =: bdo AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Date_Referred__c = null AND Status__c='Closed'];
            }                
            return complaints.Size();
        }
        catch (Exception e) 
		{
			System.Debug('e:  ' + e);
			throw new AuraHandledException(e.getMessage());    
		}
	}
    
    @AuraEnabled 
    public static long GetAverageDaysOpen(string bdo, DateTime beginDate, DateTime endDate) 
    {
        try 
        {
            List<Complaints__c> complaints = new List<Complaints__c>();
            
            
            if(bdo == 'All')
            {
                complaints = [SELECT Id, CreatedDate,End_Of_Quarter__c,End_Of_Year__c FROM Complaints__c WHERE Original_Complaint_ID__c = null AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Date_Referred__c = null AND Status__c <> 'Closed'];
            }
            else 
            {
                complaints = [SELECT Id, CreatedDate,End_Of_Quarter__c,End_Of_Year__c FROM Complaints__c WHERE Original_Complaint_ID__c = null AND BDO_For_Report__c =: bdo AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Date_Referred__c = null AND Status__c <> 'Closed' ];
            }
            long totalDaysOpen = 0;
            for(Complaints__c c : complaints)
            {
                Date d = date.newinstance(c.CreatedDate.year(), c.CreatedDate.month(), c.CreatedDate.day());
                long daysOpen = 0;
                if(beginDate.Year() == 2016 && beginDate.Month() == 4 && beginDate.Day() == 1)//All Time
                {
                    daysOpen = d.DaysBetween(date.Today());        
                }
                else
                {
                    
                    if(beginDate.Month() == 1 && beginDate.Day() == 1 && endDate.Month() == 12 && endDate.Day() == 31)//Year
                    {
                        daysOpen = d.DaysBetween(c.End_Of_Year__c);
                    }
                    else//Quarter
                    {
                        daysOpen = d.DaysBetween(c.End_Of_Quarter__c);        
                    }
                }
                totalDaysOpen = totalDaysOpen + daysOpen;
            }
            return totalDaysOpen/complaints.Size();
        }
        catch (Exception e) 
        {
            System.Debug('e:  ' + e);
            throw new AuraHandledException(e.getMessage());    
        }
    }
    
    @AuraEnabled 
    public static long GetAverageDaysToClose(string bdo, DateTime beginDate, DateTime endDate) 
    {
        try 
		{
            List<Complaints__c> complaints = new List<Complaints__c>();
            
            
            if(bdo == 'All')
            {
                complaints = [SELECT Id, Closed_Date__c,CreatedDate FROM Complaints__c WHERE Original_Complaint_ID__c = null AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Date_Referred__c = null AND Status__c='Closed' ];
            }
            else 
            {
                complaints = [SELECT Id, Closed_Date__c,CreatedDate FROM Complaints__c WHERE Original_Complaint_ID__c = null AND BDO_For_Report__c =: bdo AND CreatedDate >=: beginDate AND CreatedDate <=: endDate AND Date_Referred__c = null AND Status__c='Closed'];
            }    
            long totalDaysOpen = 0;
            for(Complaints__c c : complaints)
            {
                Date d = date.newinstance(c.CreatedDate.year(), c.CreatedDate.month(), c.CreatedDate.day());
                long daysOpen = d.DaysBetween(c.Closed_Date__c);
                totalDaysOpen = totalDaysOpen + daysOpen;

            }
            return totalDaysOpen/complaints.Size();
        }
        catch (Exception e) 
		{
			System.Debug('e:  ' + e);
			throw new AuraHandledException(e.getMessage());    
		}
    }

    @AuraEnabled
    public static string GetNewComplaintsReportUrl(string bdo, Date startDate, Date endDate)
    {
    	string url = '';
        string baseUrl = System.Url.getSalesforceBaseUrl().toExternalForm();
        Report report = [SELECT Id,Name,FolderName FROM Report WHERE Name='New Complaints Report'];
        String template = '{0}/lightning/r/Report/{1}/view?fv0={2}&fv1={3}&fv2={4}';
        List<Object> parameters = new List<Object> {baseUrl, 
            report.Id,
            EncodingUtil.urlEncode(bdo, 'UTF-8'),            
            EncodingUtil.urlEncode(startDate.format(), 'UTF-8'),
            EncodingUtil.urlEncode(endDate.format(), 'UTF-8')};
        url = String.format(template, parameters);		
        return url;
    }
    
    @AuraEnabled
    public static string GetComplaintsWithViolationsReportUrl(string bdo, Date startDate, Date endDate)
    {
    	string url = '';
        string baseUrl = System.Url.getSalesforceBaseUrl().toExternalForm();
        Report report = [SELECT Id,Name,FolderName FROM Report WHERE Name='Complaints With Violations Report'];
        String template = '{0}/lightning/r/Report/{1}/view?fv0={2}&fv1={3}&fv2={4}';
        List<Object> parameters = new List<Object> {baseUrl, 
            report.Id,
            EncodingUtil.urlEncode(bdo, 'UTF-8'),            
            EncodingUtil.urlEncode(startDate.format(), 'UTF-8'),
            EncodingUtil.urlEncode(endDate.format(), 'UTF-8')};
        url = String.format(template, parameters);		
        return url;
    }
    
    @AuraEnabled
    public static string GetReferredComplaintsReportUrl(string bdo, Date startDate, Date endDate)
    {
    	string url = '';
        string baseUrl = System.Url.getSalesforceBaseUrl().toExternalForm();
        Report report = [SELECT Id,Name,FolderName FROM Report WHERE Name='Referred Complaints Report'];
        String template = '{0}/lightning/r/Report/{1}/view?fv0={2}&fv1={3}&fv2={4}';
        List<Object> parameters = new List<Object> {baseUrl, 
            report.Id,
            EncodingUtil.urlEncode(bdo, 'UTF-8'),            
            EncodingUtil.urlEncode(startDate.format(), 'UTF-8'),
            EncodingUtil.urlEncode(endDate.format(), 'UTF-8')};
        url = String.format(template, parameters);		
        return url;
    }
    
	@AuraEnabled
    public static string GetCalEPAHandledOpenComplaintsReportUrl(string bdo, Date startDate, Date endDate)
    {
    	string url = '';
        string baseUrl = System.Url.getSalesforceBaseUrl().toExternalForm();
        Report report = [SELECT Id,Name,FolderName FROM Report WHERE Name='CalEPA Handled Open Complaints Report'];
        String template = '{0}/lightning/r/Report/{1}/view?fv0={2}&fv1={3}&fv2={4}';
        List<Object> parameters = new List<Object> {baseUrl, 
            report.Id,
            EncodingUtil.urlEncode(bdo, 'UTF-8'),            
            EncodingUtil.urlEncode(startDate.format(), 'UTF-8'),
            EncodingUtil.urlEncode(endDate.format(), 'UTF-8')};
        url = String.format(template, parameters);		
        return url;
    }
    
	@AuraEnabled
    public static string GetCalEPAHandledClosedComplaintsReportUrl(string bdo, Date startDate, Date endDate)
    {
    	string url = '';
        string baseUrl = System.Url.getSalesforceBaseUrl().toExternalForm();
        Report report = [SELECT Id,Name,FolderName FROM Report WHERE Name='CalEPA Handled Closed Complaints Report'];
        String template = '{0}/lightning/r/Report/{1}/view?fv0={2}&fv1={3}&fv2={4}';
        List<Object> parameters = new List<Object> {baseUrl, 
            report.Id,
            EncodingUtil.urlEncode(bdo, 'UTF-8'),            
            EncodingUtil.urlEncode(startDate.format(), 'UTF-8'),
            EncodingUtil.urlEncode(endDate.format(), 'UTF-8')};
        url = String.format(template, parameters);		
        return url;
    }    
}