unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Finding__c.object
<CustomObject>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Completed_By__c</fullName>
        <formula>IF(NOT(ISBLANK(Contact__c)),  Contact__r.FirstName + &apos; &apos; + Contact__r.LastName ,  CreatedBy.FirstName + &apos; &apos; +  CreatedBy.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Completed By</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Finding</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Referral__c</fullName>
        <description>Date Referred to to External Agency</description>
        <inlineHelpText>Date Referred to to External Agency</inlineHelpText>
        <label>Date of Referral</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Site_Visit__c</fullName>
        <description>Date of Site Visit</description>
        <inlineHelpText>Date of Site Visit</inlineHelpText>
        <label>Date of Site Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Enforcement_Complete__c</fullName>
        <description>Is Enforcement Complete?</description>
        <inlineHelpText>Is Enforcement Complete?</inlineHelpText>
        <label>Is Enforcement Complete</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Going_Enforcement__c</fullName>
        <description>Describe any on-going enforcement efforts</description>
        <inlineHelpText>Describe any on-going enforcement efforts</inlineHelpText>
        <label>On-Going Enforcement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Reason_for_No_Site_Visit__c</fullName>
        <description>If other was selected for reason no site visit was conducted, please provide the reason here.</description>
        <inlineHelpText>If other was selected for reason no site visit was conducted, please provide the reason here.</inlineHelpText>
        <label>Other Reason for No Site Visit</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reason_for_No_Site_Visit__c</fullName>
        <description>If no site visit was conducted, why not?</description>
        <inlineHelpText>If no site visit was conducted, why not?</inlineHelpText>
        <label>Why didn&apos;t you conduct a site visit?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complaint is outside agency jurisdiction</fullName>
                </value>
                <value>
                    <fullName>Complaint lacked sufficient information</fullName>
                </value>
                <value>
                    <fullName>Complaint was referred to another agency for handling</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral_Agency__c</fullName>
        <description>Name of the Agency to which You Referred the Finding</description>
        <inlineHelpText>Name of the Agency to which You Referred the Finding</inlineHelpText>
        <label>Who Did You Refer it to?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Referral__c</fullName>
        <inlineHelpText>Did you refer this complaint to another agency?</inlineHelpText>
        <label>Did you refer this to another agency?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Visit_Conducted__c</fullName>
        <description>Did you conduct a site visit to investigate the complaint?</description>
        <inlineHelpText>Did you conduct a site visit to investigate the complaint?</inlineHelpText>
        <label>Did you conduct a site visit?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary_of_Violations_and_enforcement__c</fullName>
        <description>Summary of violations and enforcement action taken.</description>
        <inlineHelpText>Summary of violations and enforcement action taken.</inlineHelpText>
        <label>Summary of Violations and enforcement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Violations_Related_to_Complaint__c</fullName>
        <description>Were the violations related to the complaint?</description>
        <inlineHelpText>Were the violations related to the complaint?</inlineHelpText>
        <label>Violations Related to Complaint</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violations_or_Compliance_Issues__c</fullName>
        <description>Did you find violations or compliance issues?</description>
        <inlineHelpText>Did you find violations or compliance issues?</inlineHelpText>
        <label>Violations or Compliance Issues</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <label>Finding</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Finding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{00000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/FindingPDFController.cls
public with sharing class FindingPDFController {
	public FindingDetailViewModel FindingDetailViewModel {get;set;}    

	public FindingPDFController(ApexPages.StandardController controller) 
	{
	}
	
	public PageReference LoadFindingPDF() 
    {
		string findingId = '';
        if(ApexPages.currentPage().getParameters().get('id') != null)
        {
            findingId = ApexPages.currentPage().getParameters().get('id');
        }
        else
        {
            ApplicationException e = new ApplicationException();
            e.setMessage('Missing Finding Id.');
            throw e;
        }
        FindingDetailViewModel = new FindingDetailViewModel();
		Finding__c finding = [SELECT Complaint__c,Completed_By__c,Contact__c,CreatedById, Contact__r.Name, CreatedBy.Name, CreatedBy.Title, CreatedBy.Email, CreatedBy.Phone, CreatedDate, Date_of_Referral__c,Date_of_Site_Visit__c,External_Id__c,Id,IsDeleted,Is_Enforcement_Complete__c,LastActivityDate,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Name,On_Going_Enforcement__c,Other_Reason_for_No_Site_Visit__c,Reason_for_No_Site_Visit__c,Referral_Agency__c,Referral__c,Secondary_Referral__c,Site_Visit_Conducted__c,Summary_of_Violations_and_enforcement__c,Violations_or_Compliance_Issues__c,Violations_Related_to_Complaint__c,Complaint__r.Name,Contact__r.Email,Contact__r.Title,Contact__r.Phone FROM Finding__c WHERE Id =: findingId];
        FindingDetailViewModel.FindingId = finding.Id;
        FindingDetailViewModel.FindingName = finding.Name;
        
        if(finding.Contact__c != null)
        {
            FindingDetailViewModel.CompletedBy = finding.Contact__r.Name;            
            FindingDetailViewModel.Title = finding.Contact__r.Title;
            FindingDetailViewModel.Email = finding.Contact__r.Email;
            FindingDetailViewModel.Phone = finding.Contact__r.Phone;            
        }
        else
        {
            FindingDetailViewModel.CompletedBy = finding.CreatedBy.Name;            
            FindingDetailViewModel.Title = finding.CreatedBy.Title;
            FindingDetailViewModel.Email = finding.CreatedBy.Email;
            FindingDetailViewModel.Phone = finding.CreatedBy.Phone;
        }
        
        
        if(finding.Secondary_Referral__c == 'Yes')
        {
            FindingDetailViewModel.IsSecondaryReferral = true;
        }
        else
        {
            FindingDetailViewModel.IsSecondaryReferral = false;
        }
        FindingDetailViewModel.SecondaryReferral = finding.Secondary_Referral__c;
        FindingDetailViewModel.ReferralAgency  = finding.Referral_Agency__c;
        if(finding.Date_of_Referral__c != null)
        {
            FindingDetailViewModel.DateOfReferral  = DateTime.newInstance(finding.Date_of_Referral__c.year(),finding.Date_of_Referral__c.month(),finding.Date_of_Referral__c.day()).format('MM/dd/yyyy');
        }
        else
        {
            FindingDetailViewModel.DateOfReferral = '';
        }
        if(finding.Site_Visit_Conducted__c == 'Yes')
        {
            FindingDetailViewModel.IsSiteVisit = true;
        }
        else
        {
            FindingDetailViewModel.IsSiteVisit = false;
        }
        FindingDetailViewModel.SiteVisitConducted  = finding.Site_Visit_Conducted__c;
        if(finding.Date_of_Site_Visit__c != null)
        {
            FindingDetailViewModel.DateOfSiteVisit  = DateTime.newInstance(finding.Date_of_Site_Visit__c.year(),finding.Date_of_Site_Visit__c.month(),finding.Date_of_Site_Visit__c.day()).format('MM/dd/yyyy');
        }
        else
        {
            FindingDetailViewModel.DateOfSiteVisit = '';
        }
        if(finding.Reason_for_No_Site_Visit__c == 'Other')
        {
            FindingDetailViewModel.ReasonForNoSiteVisit  = finding.Other_Reason_for_No_Site_Visit__c;
        }
        else
        {
            FindingDetailViewModel.ReasonForNoSiteVisit  = finding.Reason_for_No_Site_Visit__c;
        }
        
        FindingDetailViewModel.ViolationsOrComplianceIssues  = finding.Violations_or_Compliance_Issues__c;
        if(finding.Violations_or_Compliance_Issues__c == 'Yes')
        {
            FindingDetailViewModel.IsViolationsOrComplianceIssues  = true;
        }
        else
        {
            FindingDetailViewModel.IsViolationsOrComplianceIssues  = false;
        }
        
        FindingDetailViewModel.SummaryOfViolationsAndEnforcement  = finding.Summary_of_Violations_and_enforcement__c;
        FindingDetailViewModel.ViolationsRelatedToComplaint  = finding.Violations_Related_to_Complaint__c;
        if(finding.Is_Enforcement_Complete__c == 'Yes')
        {
            FindingDetailViewModel.IsIsEnforcementComplete  = true;
        }
        else
        {
            FindingDetailViewModel.IsIsEnforcementComplete  = false;
        }
        FindingDetailViewModel.IsEnforcementComplete  = finding.Is_Enforcement_Complete__c;
        FindingDetailViewModel.OnGoingEnforcement  = finding.On_Going_Enforcement__c;

        List<Attachment> attachments = [SELECT Id, Name, BodyLength, ContentType FROM Attachment WHERE ParentID =: finding.Id];
        FindingDetailViewModel.Attachments = attachments;


        return null;
    }

	
}