unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>Air__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you have a general air pollution complaint, which includes open burning, stationary source emissions, fugitive dust emissions, and gasoline nozzles.</inlineHelpText>
        <label>Air</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_Address__c</fullName>
        <inlineHelpText>Complaint location address or intersection</inlineHelpText>
        <label>Complaint Location Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_City__c</fullName>
        <inlineHelpText>City of the complaint location</inlineHelpText>
        <label>Complaint Location City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_State__c</fullName>
        <label>Complaint Location State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California</fullName>
                    <default>true</default>
                    <label>California</label>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Complaint_Location_Zip_Code__c</fullName>
        <inlineHelpText>Zip Code where the complaint occurred</inlineHelpText>
        <label>Complaint Location Zip Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/GeoLocation_test2.cls
@isTest()
public class GeoLocation_test2 {
    //public static testMethod void myUnitTest(){
      //  test.startTest();
       // List<Complaints__c> complaints = new List<Complaints__c>();
       // Complaints__c c = new Complaints__c();
       // c.Air__c = true;
       // c.Complaint_Location_Address__c = '1001 I Street';
       // c.Complaint_Location_City__c = 'Sacramento'; 
       // c.Complaint_Location_State__c = 'CA';
       // c.Complaint_Location_Zip_Code__c = '95812';
       // complaints.add(c);
       // insert complaints;
        
        //GeoLocation geoloc = new GeoLocation();
        //geoloc.geoLocationUpdate(complaints,true);
        //geoloc.geoLocationUpdate(complaints,false);
        
       // test.stopTest();
    //}
}