unpackaged/objects/Complaint_Assignment__c.object
<CustomObject>
    <description>Object to track BDO level status and &quot;ownership&quot;</description>
    <fields>
        <fullName>Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Complaint Assignments</relationshipLabel>
        <relationshipName>Complaint_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Complaint Assignment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Complaint Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>Complaint_Location_Address__c</fullName>
        <inlineHelpText>Complaint location address or intersection</inlineHelpText>
        <label>Complaint Location Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_City__c</fullName>
        <inlineHelpText>City of the complaint location</inlineHelpText>
        <label>Complaint Location City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_State__c</fullName>
        <label>Complaint Location State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California</fullName>
                    <default>true</default>
                    <label>California</label>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Complaint_Location_Zip_Code__c</fullName>
        <inlineHelpText>Zip Code where the complaint occurred</inlineHelpText>
        <label>Complaint Location Zip Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Toxic_Substances__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark this check box if the complaint is a toxic substances related issue</inlineHelpText>
        <label>Toxic Substances</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Water__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark this check box if the complaint is a water related issue</inlineHelpText>
        <label>Water</label>
        <type>Checkbox</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/ComplaintTriggerHandler.cls
public class ComplaintTriggerHandler extends TriggerHandler 
{
    public ComplaintManager CmplntMngr { get; set; }
    public ICallout2 CO { get; set; }

    
    public ComplaintTriggerHandler(ICallout2 callout) 
    {   
        CmplntMngr = new ComplaintManager(callout);
        CO = callout;
    }

    protected override void afterInsert() //Bulkified
    {
        system.debug('afterInsert 1');
        if(TriggerManager.runAfterInsertOnce())
        {
            Set<Id> allComplaintIds = new Set<Id>();
            Set<Id> needsAddressStandardization = new Set<Id>();
            Set<Id> needsAssignment = new Set<Id>();
            system.debug('afterInsert 2');
            for(Complaints__c complaint: (List<Complaints__c>)trigger.new)
            {     
                allComplaintIds.Add(complaint.Id);
                if((complaint.Complaint_Location_City__c != null || complaint.Complaint_Location_Zip_Code__c != null))
                {
                    system.debug('afterInsert 3');
                    needsAddressStandardization.Add(complaint.Id);
                }
                else
                {
                    system.debug('afterInsert 4');
                    needsAssignment.Add(complaint.Id);
                }
            }  
            if(needsAddressStandardization.size() > 0)
            {
                system.debug('afterInsert 5');
                ComplaintManager.StandardizeAddress(needsAddressStandardization , true, 'Region 5');  //Region 5 is just injected for unit testing.           
            }
            if(needsAssignment.size() > 0)
            {
                system.debug('afterInsert 6');
                ComplaintManager.CreateToxicsAndWaterAssignments(needsAssignment);
            }
            if(allComplaintIds.size() > 0)
            {
                system.debug('afterInsert 6');
                if(!Test.isRunningTest())
                {
                    ComplaintManager.CreateComplaintPDF(allComplaintIds);                    
                }
            }
        }
    }
        
    protected override void afterUpdate() 
    {
        if(TriggerManager.runAfterUpdateOnce())
        {
            Set<Id> needsAddressStandardization = new Set<Id>();
            Set<Id> needsAssignment = new Set<Id>();
            for(Complaints__c complaint : (List<Complaints__c>)trigger.new)
            {                    
                Complaints__c oldComplaint = (Complaints__c)trigger.oldMap.get(complaint.Id);
                if((complaint.Complaint_Location_City__c != null || complaint.Complaint_Location_Zip_Code__c != null))
                {
                    if(complaint.Complaint_Location_Address__c != oldComplaint.Complaint_Location_Address__c
                        || complaint.Complaint_Location_City__c != oldComplaint.Complaint_Location_City__c
                        || complaint.Complaint_Location_State__c != oldComplaint.Complaint_Location_State__c
                        || complaint.Complaint_Location_Zip_Code__c != oldComplaint.Complaint_Location_Zip_Code__c)
                    {                            
                        needsAddressStandardization.Add(complaint.Id);
                    }
                    else
                    {
                        if((oldComplaint.Toxic_Substances__c != complaint.Toxic_Substances__c) || (oldComplaint.Water__c != complaint.Water__c))
                        {
                            needsAssignment.Add(complaint.Id);
                        }
                    }
                }
                else
                {
                    if((oldComplaint.Toxic_Substances__c != complaint.Toxic_Substances__c) || (oldComplaint.Water__c != complaint.Water__c))
                    {
                        needsAssignment.Add(complaint.Id);
                    }
                }
            }
            if(needsAddressStandardization.size() > 0)
            {                
                ComplaintManager.StandardizeAddress(needsAddressStandardization , true, 'Region 5');  //Region 5 is just injected for unit testing.           
            }
            if(needsAssignment.size() > 0)
            {
                ComplaintManager.CreateToxicsAndWaterAssignments(needsAssignment);
            }
        }
    }
    
    protected override void beforeDelete()
    {
        List<Id> complaintIds = new List<Id>();
        for(Complaints__c complaint: (List<Complaints__c >)Trigger.Old) 
        {
            complaintIds.Add(complaint.Id);
        }
        
        List<Complaint_Assignment__c> complaintAssignmentsToDelete = [SELECT Id FROM Complaint_Assignment__c WHERE Complaint__c in: complaintIds];
        delete complaintAssignmentsToDelete;
    }
}