unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Receive_Date__c</fullName>
        <label>Actual Receive Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BDO_For_Report__c</fullName>
        <formula>if( Number_of_BDOs__c   &gt; 1, &apos;Multi-BDO&apos;
, if( Air__c ,&apos;Air&apos;
     , if( Solid_Waste__c , &apos;Solid Waste&apos;
          , if( Pesticides__c , &apos;Pesticides&apos;
               , if( Toxic_Substances__c ,&apos;Toxic Substances&apos;
                    ,if( Water__c ,&apos;Water&apos;,&apos;&apos;
                     )
                  )
             )
        )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BDO For Report</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Complaint_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Complaint ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/DashboardComplaintsByBDOChart.cls
public class DashboardComplaintsByBDOChart 
{
    //Comment
    @AuraEnabled
    public static String GetComplaintsByBDOAllTime()
    {
        List<Complaints__c> complaints = [SELECT Id, BDO_For_Report__c FROM Complaints__c WHERE Original_Complaint_ID__c = null];
        Map<String,Integer> mapLeadSource = new Map<String,Integer>();
        
        for(Complaints__c l : complaints)
        {
            if(mapLeadSource.containsKey(l.BDO_For_Report__c))
            {
                mapLeadSource.put(l.BDO_For_Report__c, mapLeadSource.get(l.BDO_For_Report__c)+1) ;
            }
            else
            {
                mapLeadSource.put(l.BDO_For_Report__c, 1) ;        
            }
        }
        list<RadarDataWrapper> radarData = new list<RadarDataWrapper>();
        for(String key : mapLeadSource.keySet())
        {            
            RadarDataWrapper rdw = new RadarDataWrapper();
            rdw.name=key;
            rdw.y=mapLeadSource.get(key);
            radarData.add(rdw);
        }
        for(RadarDataWrapper rdw : radarData)
        {            
            //Take Count
            integer c = rdw.y;
            //Divide By Complaint Count
            decimal d = decimal.ValueOf(c)/decimal.ValueOf(complaints.size());
            //Multiply By 100
            d = d * 100;
            //Take Integer Part
            Long l = d.round(System.RoundingMode.UP);
            rdw.y = l.intValue();

        }
        System.Debug('All Time RadarData:  ' + radarData);
        radarData.sort();
        return System.json.serialize(radarData);
    }

    @AuraEnabled
    public static String GetComplaintsByBDOThisYear()
    {
        List<Complaints__c> complaints = [SELECT Id, BDO_For_Report__c FROM Complaints__c WHERE Original_Complaint_ID__c = null AND Actual_Receive_Date__c = THIS_YEAR];
        Map<String,Integer> mapLeadSource = new Map<String,Integer>();
        
        for(Complaints__c l : complaints)
        {
            if(mapLeadSource.containsKey(l.BDO_For_Report__c))
            {
                mapLeadSource.put(l.BDO_For_Report__c, mapLeadSource.get(l.BDO_For_Report__c)+1) ;
            }
            else
            {
                mapLeadSource.put(l.BDO_For_Report__c, 1) ;        
            }
        }
        list<RadarDataWrapper> radarData = new list<RadarDataWrapper>();
        
        for(String key : mapLeadSource.keySet())
        {            
            RadarDataWrapper rdw = new RadarDataWrapper();
            rdw.name=key;
            rdw.y=mapLeadSource.get(key);
            radarData.add(rdw);
        }
        for(RadarDataWrapper rdw : radarData)
        {            
            //Take Count
            integer c = rdw.y;
            //Divide By Complaint Count
            decimal d = decimal.ValueOf(c)/decimal.ValueOf(complaints.size());
            //Multiply By 100
            d = d * 100;
            //Take Integer Part
            Long l = d.round(System.RoundingMode.UP);
            rdw.y = l.intValue();

        }
		System.Debug('This Year RadarData:  ' + radarData);
        radarData.sort();
        return System.json.serialize(radarData);
    }
    
    class RadarDataWrapper implements Comparable
    {
       @AuraEnabled
       public String name;
       @AuraEnabled
       public integer y;

       public Integer compareTo(Object compareTo) 
       {
            // Cast argument to RadarDataWrapper
            RadarDataWrapper compareTo2 = (RadarDataWrapper)compareTo;
            
            // The return value of 0 indicates that both elements are equal.
            Integer returnValue = 0;
            if (name > compareTo2.Name) 
            {
                // Set return value to a positive value.
                returnValue = 1;
            } 
            else if (name < compareTo2.Name) 
            {
                // Set return value to a negative value.
                returnValue = -1;
            }
            
            return returnValue;       
        }
    }

}