unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>Air__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you have a general air pollution complaint, which includes open burning, stationary source emissions, fugitive dust emissions, and gasoline nozzles.</inlineHelpText>
        <label>Air</label>
        <type>Checkbox</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <description>Parent complaint Record Type..</description>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IsRegistered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Registered</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Finding__c.object
<CustomObject>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Finding</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Referral__c</fullName>
        <description>Date Referred to to External Agency</description>
        <inlineHelpText>Date Referred to to External Agency</inlineHelpText>
        <label>Date of Referral</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Site_Visit__c</fullName>
        <description>Date of Site Visit</description>
        <inlineHelpText>Date of Site Visit</inlineHelpText>
        <label>Date of Site Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Partner__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>External Partner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Enforcement_Complete__c</fullName>
        <description>Is Enforcement Complete?</description>
        <inlineHelpText>Is Enforcement Complete?</inlineHelpText>
        <label>Is Enforcement Complete</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Going_Enforcement__c</fullName>
        <description>Describe any on-going enforcement efforts</description>
        <inlineHelpText>Describe any on-going enforcement efforts</inlineHelpText>
        <label>On-Going Enforcement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Reason_for_No_Site_Visit__c</fullName>
        <description>If other was selected for reason no site visit was conducted, please provide the reason here.</description>
        <inlineHelpText>If other was selected for reason no site visit was conducted, please provide the reason here.</inlineHelpText>
        <label>Other Reason for No Site Visit</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reason_for_No_Site_Visit__c</fullName>
        <description>If no site visit was conducted, why not?</description>
        <inlineHelpText>If no site visit was conducted, why not?</inlineHelpText>
        <label>Why didn&apos;t you conduct a site visit?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complaint is outside agency jurisdiction</fullName>
                </value>
                <value>
                    <fullName>Complaint lacked sufficient information</fullName>
                </value>
                <value>
                    <fullName>Complaint was referred to another agency for handling</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral_Agency__c</fullName>
        <description>Name of the Agency to which You Referred the Finding</description>
        <inlineHelpText>Name of the Agency to which You Referred the Finding</inlineHelpText>
        <label>Who Did You Refer it to?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Referral__c</fullName>
        <inlineHelpText>Did you refer this complaint to another agency?</inlineHelpText>
        <label>Did you refer this to another agency?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Visit_Conducted__c</fullName>
        <description>Did you conduct a site visit to investigate the complaint?</description>
        <inlineHelpText>Did you conduct a site visit to investigate the complaint?</inlineHelpText>
        <label>Did you conduct a site visit?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary_of_Violations_and_enforcement__c</fullName>
        <description>Summary of violations and enforcement action taken.</description>
        <inlineHelpText>Summary of violations and enforcement action taken.</inlineHelpText>
        <label>Summary of Violations and enforcement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Violations_Related_to_Complaint__c</fullName>
        <description>Were the violations related to the complaint?</description>
        <inlineHelpText>Were the violations related to the complaint?</inlineHelpText>
        <label>Violations Related to Complaint</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violations_or_Compliance_Issues__c</fullName>
        <description>Did you find violations or compliance issues?</description>
        <inlineHelpText>Did you find violations or compliance issues?</inlineHelpText>
        <label>Violations or Compliance Issues</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <label>Finding</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Finding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>External Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SelectedContacts__c</fullName>
        <label>SelectedContacts</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{00000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/UnitTestHelper.cls
public with sharing class UnitTestHelper 
{
    static Integer s_num = 1; 

    public static Account CreateTestAccount()
    {
        RecordType calEPAPartnerAgencyAccountRecordType = [SELECT Id, Name, SobjectType FROM RecordType WHERE SobjectType = 'Account' AND Name =: 'CalEPA Partner Agency' Limit 1 ];
        Account testAccount = new Account(RecordTypeId = calEPAPartnerAgencyAccountRecordType.Id, Name = 'Test Account');
        insert testAccount;
        return testAccount;
    }

    public static Account CreateTestPersonAccount()
    {
        RecordType complainantAccountRecordType = [SELECT Id, Name, SobjectType FROM RecordType WHERE SobjectType = 'Account' AND Name =: 'Complainant' Limit 1 ];
        Account testAccount = new Account(RecordTypeId = complainantAccountRecordType.Id, FirstName = 'Test', LastName = 'Complainant');
        insert testAccount;
        return testAccount;
    }

    public static Contact CreateTestCalEPAPartnerContact(string accountId, string email)
    {       
        RecordType calEPAPartnerContactRecordType = [SELECT Id, Name, SobjectType FROM RecordType WHERE SobjectType = 'Contact' AND Name =: 'CalEPA Partner' Limit 1 ];
        Contact testContact = new Contact(RecordTypeId = calEPAPartnerContactRecordType.Id, FirstName = 'Test', LastName = 'Contact', AccountId = accountId, IsRegistered__c = true, Email = email );
        insert testContact;
        return testContact;
    }

    public static Complaints__c CreateTestComplaint()
    {
        RecordType parentComplaintRecordType = [SELECT Id, Name, SobjectType FROM RecordType WHERE SobjectType = 'Complaints__c' AND Name =: 'Parent' Limit 1 ];
        Complaints__c testComplaint = new Complaints__c(RecordTypeId = parentComplaintRecordType.Id, Air__c = true);
        insert testComplaint;
        return testComplaint;
    }

    public static Referral__c CreateTestReferral(string complaintId, string accountId, string contactIds)
    {
        Referral__c testReferral = new Referral__c(Complaint__c = complaintId, External_Partner__c = accountId, SelectedContacts__c=contactIds);
        insert testReferral;
        return testReferral;    
    }

    public static Finding__c CreateTestFinding(string complaintId, string referralId, string contactId)
    {
        Finding__c testFinding = new Finding__c();
        testFinding.Complaint__c = complaintId;
        testFinding.Contact__c = contactId;
        testFinding.Date_of_Referral__c = Date.valueOf('2017-01-01 00:00:00');
        testFinding.Date_of_Site_Visit__c = Date.valueOf('2017-01-01 00:00:00');        
        testFinding.Is_Enforcement_Complete__c = 'Yes';
        testFinding.On_Going_Enforcement__c = '';
        testFinding.Other_Reason_for_No_Site_Visit__c = '';
        testFinding.Reason_for_No_Site_Visit__c = '';
        testFinding.Referral_Agency__c = 'Lorem Ipsum';
        testFinding.Referral__c = referralId;
        testFinding.Secondary_Referral__c = 'Yes';
        testFinding.Site_Visit_Conducted__c = 'Yes';
        testFinding.Summary_of_Violations_and_enforcement__c = 'Lorem Ipsum';
        testFinding.Violations_or_Compliance_Issues__c = 'No';
        testFinding.Violations_Related_to_Complaint__c = null;
        insert testFinding;
        return testFinding; 
    }

    public static Document CreateTestDocument(string documentName)
    {
        Document document;
        document = new Document();
        document.Body = Blob.valueOf('Some Text');
        document.ContentType = 'application/pdf';
        document.DeveloperName = 'my_document';
        document.IsPublic = true;
        document.Name = documentName;
        document.FolderId = [select id from folder where name = 'Temp'].id;
        insert document;
        return document;    
    }
    
    public static string GetFakeId(Schema.SObjectType sot)
    {
      String result = String.valueOf(s_num++);
      return sot.getDescribe().getKeyPrefix() + '0'.repeat(12-result.length()) + result;
    }   
}