unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Receive_Date__c</fullName>
        <label>Actual Receive Date</label>
        <type>DateTime</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Finding__c.object
<CustomObject>
    <fields>
        <fullName>Complaint__c</fullName>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Enforcement_Complete__c</fullName>
        <description>Is Enforcement Complete?</description>
        <inlineHelpText>Is Enforcement Complete?</inlineHelpText>
        <label>Is Enforcement Complete</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Referral__c</fullName>
        <inlineHelpText>Did you refer this complaint to another agency?</inlineHelpText>
        <label>Did you refer this to another agency?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Visit_Conducted__c</fullName>
        <description>Did you conduct a site visit to investigate the complaint?</description>
        <inlineHelpText>Did you conduct a site visit to investigate the complaint?</inlineHelpText>
        <label>Did you conduct a site visit?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violations_or_Compliance_Issues__c</fullName>
        <description>Did you find violations or compliance issues?</description>
        <inlineHelpText>Did you find violations or compliance issues?</inlineHelpText>
        <label>Violations or Compliance Issues</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <label>Finding</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Finding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/DashboardCompsWithEnfControllerTests.cls
@isTest
public class DashboardCompsWithEnfControllerTests 
{
    /*static testMethod void Test()
    {
        //Arrange
        string expected = '';

        //Act
        Test.startTest();        
        Test.stopTest();
        
        string actual = '';
        
        //Assert
        System.assertEquals(expected, actual); 
    }*/

    static testMethod void GetComplaintsWithEnforcementActionTest()
    {
        //Arrange
        Complaints__c complaint = new Complaints__c(Actual_Receive_Date__c=date.today());
        insert complaint;
        Finding__c finding = new Finding__c(Complaint__c = complaint.Id, Violations_or_Compliance_Issues__c='Yes',Is_Enforcement_Complete__c='Yes', Secondary_Referral__c='No', Site_Visit_Conducted__c='Yes');
        insert finding;
        string expected = finding.Id;



        //Act
        Test.startTest();
        string temp = DashboardCompsWithEnforcementController.GetComplaintsWithEnforcementAction();
        System.Debug(temp);
        List<DashboardCompsWithEnforcementWrapper> tempObj = (List<DashboardCompsWithEnforcementWrapper>)JSON.deserialize(temp, List<DashboardCompsWithEnforcementWrapper>.class);
        string actual = tempObj[0].Id;
        Test.stopTest();
        
        //Assert
        System.assertEquals(expected, actual); 
    }

    class DashboardCompsWithEnforcementWrapper
    {
       @AuraEnabled
       public String Id;
       @AuraEnabled
       public String URL;
       @AuraEnabled
       public String ComplaintNumber;
       @AuraEnabled
       public string CreatedDate;
    }
}