unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>Air__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you have a general air pollution complaint, which includes open burning, stationary source emissions, fugitive dust emissions, and gasoline nozzles.</inlineHelpText>
        <label>Air</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complainant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complainant</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Complaints</relationshipLabel>
        <relationshipName>Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_Address__c</fullName>
        <inlineHelpText>Complaint location address or intersection</inlineHelpText>
        <label>Complaint Location Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_City__c</fullName>
        <inlineHelpText>City of the complaint location</inlineHelpText>
        <label>Complaint Location City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_State__c</fullName>
        <label>Complaint Location State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California</fullName>
                    <default>true</default>
                    <label>California</label>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Complaint_Location_Zip_Code__c</fullName>
        <inlineHelpText>Zip Code where the complaint occurred</inlineHelpText>
        <label>Complaint Location Zip Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Source__c</fullName>
        <label>Complaint Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>In Person</fullName>
                </value>
                <value>
                    <fullName>Self Generated</fullName>
                </value>
                <value>
                    <fullName>Hardcopy Letter</fullName>
                </value>
                <value>
                    <fullName>API</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pesticides__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark this check box if the complaint is a pesticides related issue</inlineHelpText>
        <label>Pesticides</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Solid_Waste__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark this check box if the complaint is a solid waste issue</inlineHelpText>
        <label>Solid Waste</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Toxic_Substances__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark this check box if the complaint is a toxic substances related issue</inlineHelpText>
        <label>Toxic Substances</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Water__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark this check box if the complaint is a water related issue</inlineHelpText>
        <label>Water</label>
        <type>Checkbox</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <recordTypes>
        <fullName>Air</fullName>
        <active>true</active>
        <description>Air Complaint Record Type.</description>
        <label>Air</label>
    </recordTypes>
    <recordTypes>
        <fullName>Pesticides</fullName>
        <active>true</active>
        <description>Pesticide complaint Record Type.</description>
        <label>Pesticides</label>
    </recordTypes>
    <recordTypes>
        <fullName>Water</fullName>
        <active>true</active>
        <description>Water Complaint Record Type.</description>
        <label>Water</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/CreateComplaintFromCaseController.cls
public class CreateComplaintFromCaseController 
{
    @AuraEnabled 
    public static Map<string, string> GetDescription(string caseId) 
	{
        Map<String, String> returnMap = new Map<String, String>();
		Case c = [SELECT Id, Description,Contact.FirstName,Contact.LastName,Contact.Email,Contact.Phone,Contact.MobilePhone,CreatedDate FROM Case WHERE Id=:caseId];
        returnMap.put('Description', c.Description);
        returnMap.put('FirstName', c.Contact.FirstName);
        returnMap.put('LastName', c.Contact.LastName);
        returnMap.put('Email', c.Contact.Email);
        returnMap.put('Phone', c.Contact.Phone);
        returnMap.put('MobilePhone', c.Contact.MobilePhone);
        returnMap.put('CreatedDate', string.valueOfGmt(c.CreatedDate));
        return returnMap;
	}
    
    @AuraEnabled 
    public static string Save(string air,string pesticides,string solidWaste,string toxicSubstances,string water,string firstName,string lastName,string email,string phone,string mobilePhone,string street,string city,string zipCode,string state,string description)	 
	{  
		try 
		{
            Complaints__c complaint = new Complaints__c();
            complaint.Complaint_Source__c = 'Email';
            if(air=='true')
            {
            	complaint.Air__c = true;
            }
            if(pesticides=='true')
            {
            	complaint.Pesticides__c =  true;
            }
			if(solidWaste=='true')
            {                
            	complaint.Solid_Waste__c =  true;
            }
			if(toxicSubstances=='true')
            {                
            	complaint.Toxic_Substances__c =  true;
            }
			if(water=='true')
            {                
            	complaint.Water__c =  true;
            }
            complaint.Complaint_Location_Address__c =  street;
            complaint.Complaint_Location_City__c =  city;
            complaint.Complaint_Location_Zip_Code__c =  zipCode;
            complaint.Complaint_Location_State__c =  state;
            complaint.Description__c =  description;            
            RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType='Account' AND Name='Complainant'];
			if(email != null)
            {
                List<Account> accounts = [SELECT Id FROM Account WHERE RecordTypeId =: rt.Id AND PersonEmail=:email AND IsPersonAccount = true];
                if(accounts.Size() > 0)    
                {
                    complaint.Complainant__c = accounts[0].Id;
                }
            }
            if(complaint.Complainant__c == null && lastName != null)
            {
                Account a = new Account();
                a.RecordTypeId = rt.Id;
                a.PersonEmail = email;
                a.FirstName = firstName;
                a.LastName = lastName;
                a.Phone = phone;
                a.PersonMobilePhone = mobilePhone;
                insert a;
                complaint.Complainant__c = a.Id;
            }
			insert complaint;
            return complaint.Id;
    	}
		catch (DMLException de) 
		{
			String message = de.getDmlMessage(0);
			throw new AuraHandledException(message);    
		} 
		catch (Exception e) 
		{
			throw new AuraHandledException(e.getMessage());    
		}
    	finally 
		{
        	// Something executed whether there was an error or not
    	}       
    }  
}