unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>CalEnviroScreen_Score_Percentile_Rank__c</fullName>
        <label>CalEnviroScreen Score Percentile Rank</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CalEnviroScreen_Score__c</fullName>
        <label>CalEnviroScreen Score</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Census_Tract_Number__c</fullName>
        <label>Census Tract Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_Address__c</fullName>
        <inlineHelpText>Complaint location address or intersection</inlineHelpText>
        <label>Complaint Location Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_City__c</fullName>
        <inlineHelpText>City of the complaint location</inlineHelpText>
        <label>Complaint Location City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_County__c</fullName>
        <inlineHelpText>County where the complaint occurred</inlineHelpText>
        <label>Complaint Location County</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alameda County</fullName>
                </value>
                <value>
                    <fullName>Alpine County</fullName>
                </value>
                <value>
                    <fullName>Amador County</fullName>
                </value>
                <value>
                    <fullName>Butte County</fullName>
                </value>
                <value>
                    <fullName>Calaveras County</fullName>
                </value>
                <value>
                    <fullName>Colusa County</fullName>
                </value>
                <value>
                    <fullName>Contra Costa County</fullName>
                </value>
                <value>
                    <fullName>Del Norte County</fullName>
                </value>
                <value>
                    <fullName>El Dorado County</fullName>
                </value>
                <value>
                    <fullName>Fresno County</fullName>
                </value>
                <value>
                    <fullName>Glenn County</fullName>
                </value>
                <value>
                    <fullName>Humboldt County</fullName>
                </value>
                <value>
                    <fullName>Imperial County</fullName>
                </value>
                <value>
                    <fullName>Inyo County</fullName>
                </value>
                <value>
                    <fullName>Kern County</fullName>
                </value>
                <value>
                    <fullName>Kings County</fullName>
                </value>
                <value>
                    <fullName>Lake County</fullName>
                </value>
                <value>
                    <fullName>Lassen County</fullName>
                </value>
                <value>
                    <fullName>Los Angeles County</fullName>
                </value>
                <value>
                    <fullName>Madera County</fullName>
                </value>
                <value>
                    <fullName>Marin County</fullName>
                </value>
                <value>
                    <fullName>Mariposa County</fullName>
                </value>
                <value>
                    <fullName>Mendocino County</fullName>
                </value>
                <value>
                    <fullName>Merced County</fullName>
                </value>
                <value>
                    <fullName>Modoc County</fullName>
                </value>
                <value>
                    <fullName>Mono County</fullName>
                </value>
                <value>
                    <fullName>Monterey County</fullName>
                </value>
                <value>
                    <fullName>Napa County</fullName>
                </value>
                <value>
                    <fullName>Nevada County</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Complaint_Location_State__c</fullName>
        <label>Complaint Location State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California</fullName>
                    <default>true</default>
                    <label>California</label>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Complaint_Location_Zip_Code__c</fullName>
        <inlineHelpText>Zip Code where the complaint occurred</inlineHelpText>
        <label>Complaint Location Zip Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drinking_Water__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Bad taste, odors, or contamination in water supplied to your house or business; or concerns about your cityâ€™s water supply system or your municipal water supplier operations.</inlineHelpText>
        <label>Drinking Water</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EJ_Complaint__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Does the complaint have to do with Environmental Justice issues?</inlineHelpText>
        <label>EJ Complaint</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Regional_Water_Board__c</fullName>
        <label>Regional Water Board</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Toxic_Substances__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark this check box if the complaint is a toxic substances related issue</inlineHelpText>
        <label>Toxic Substances</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Water_Quality__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Problems  or pollution in a stream, river, lake, wetlands, bay, groundwater basin, or the ocean resulting from discharges of polluted water or stormwater, or from other activities such as construction, grading, and excavations.</inlineHelpText>
        <label>Water Quality</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Water_Rights__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Water diversions from a stream, river, or lake, or extractions of groundwater that may be unauthorized or illegal, may be impacting your water rights, may be wasteful and unreasonable use of water, or may be impacting fish, wildlife or habitats.</inlineHelpText>
        <label>Water Rights</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Water__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark this check box if the complaint is a water related issue</inlineHelpText>
        <label>Water</label>
        <type>Checkbox</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/ComplaintManager.cls
public class ComplaintManager
{
    public ICallout2 CllOut { get; set; }
    
    public ComplaintManager(ICallout2 c)
    {
        CllOut = c;
    }
    
    @future(callout=true)
    public static void StandardizeAddress(Set<id> complaintIds, boolean updateContact, string region)
    {       
        IGeoLocationManager2 glm = null;
        CalEnviroScreen3Manager ces3m = null;
        RegionalBoardManager rbm = null;
        
        if(Test.isRunningTest())
        {
            glm = new MockGeoLocationManager2();
            ces3m = new CalEnviroScreen3Manager();
            rbm = new RegionalBoardManager();
        }
        else
        {
            ICallout2 callout = new Callout2();
            glm = new GeoLocationManager2(callout);
            ces3m = new CalEnviroScreen3Manager(callout);
            rbm = new RegionalBoardManager(callout);
        }        
        List<Complaints__c> complaints = [SELECT Id
                                                  , Complaint_Location_Address__c
                                                  , Complaint_Location_City__c
                                                  , Complaint_Location_State__c
                                                  , Complaint_Location_Zip_Code__c
                                                  , Complaint_Location_County__c
                                                  , Complaint_Location__Latitude__s
                                                  , Complaint_Location__Longitude__s
                                                  , Regional_Water_Board__c
                                                  , Water_Rights__c
                                                  , Drinking_Water__c
                                                  , Water_Quality__c
                                                  ,  Water__c
                                                  , Toxic_Substances__c
                                                  FROM Complaints__c WHERE Id in: complaintIds FOR UPDATE];
        List<QueueSobject> queues = [SELECT Id, QueueId FROM QueueSobject WHERE SobjectType = 'Complaints__c'];
        Set<Id> qIds = new Set<Id>();
        for(QueueSobject qs: queues)
        {           
            qIds.add(qs.QueueId);
        }
        
        List<Group> groups = [SELECT Id, Type, Name FROM Group WHERE Type = 'Queue' AND Id in: qIds ];
        
                                                           
        for(Complaints__c complaint : complaints)
        {            
            GeoLocation2 geoLocation = new GeoLocation2();  
            if((complaint.Complaint_Location_City__c != null || complaint.Complaint_Location_Zip_Code__c != null))
            {
                geoLocation.StreetAddress = complaint.Complaint_Location_Address__c;
                geoLocation.City = complaint.Complaint_Location_City__c;
                geoLocation.State = complaint.Complaint_Location_State__c;
                geoLocation.ZipCode = complaint.Complaint_Location_Zip_Code__c;

                geoLocation = glm.StandardizeAddress(geoLocation);
        
                if(geoLocation.City != null && geoLocation.City != '')
                {
                    complaint.Complaint_Location_Address__c = geoLocation.StreetAddress;
                    complaint.Complaint_Location_City__c = geoLocation.City;
                    complaint.Complaint_Location_State__c = geoLocation.State;            
                    complaint.Complaint_Location_Zip_Code__c = geoLocation.ZipCode;
                    complaint.Complaint_Location_County__c = geoLocation.County;
                    complaint.Complaint_Location__Latitude__s = geoLocation.Latitude;
                    complaint.Complaint_Location__Longitude__s = geoLocation.Longitude;
                    if(geoLocation.Latitude != null && geoLocation.Longitude != null)
                    {                    
                        CalEnviroScreen3Manager.CalEnviroScreen3Result calEnviroScreen3Result = ces3m.GetCalEnvroScreen3Result(geoLocation.Latitude, geoLocation.Longitude);
                        if(calEnviroScreen3Result != null)
                        {
                            if(calEnviroScreen3Result.Features != null)
                            {
                                if(calEnviroScreen3Result.Features.Size() > 0)
                                {
                                    if(calEnviroScreen3Result.Features[0].Attributes != null)
                                {
                                    complaint.Census_Tract_Number__c = calEnviroScreen3Result.Features[0].Attributes.L0CalEnviroScreen_3_0_tract;
                                    complaint.CalEnviroScreen_Score__c = calEnviroScreen3Result.Features[0].Attributes.L0CalEnviroScreen_3_0_CIscore;
                                    complaint.CalEnviroScreen_Score_Percentile_Rank__c =   String.valueOf(calEnviroScreen3Result.Features[0].Attributes.L0CalEnviroScreen_3_0_PCTLrange);
                                    if(calEnviroScreen3Result.Features[0].Attributes.L0CalEnviroScreen_3_0_CIscoreP> 75)
                                    {
                                        complaint.EJ_Complaint__c = true;
                                    }
                                }
                                }
                            }
                        }
                        string regionalBoard = rbm.GetRegionalBoard(geoLocation);            
                        complaint.Regional_Water_Board__c =  regionalBoard;
                        if(complaint.Water__c)
                        {
                            LaunchSetWaterContactAndNotifyFlow(complaint.Id,complaint.Regional_Water_Board__c);
                        }
                    }
                    if(complaint.Toxic_Substances__c)
                    {
                        LaunchUpdateToxicsRegionFlow(complaint.Id, complaint.Complaint_Location_County__c);
                    }            
                }
                else
                {
                    //Just in case the Geocoding didn't work.
                    if(complaint.Water__c)
                    {
                        LaunchSetWaterContactAndNotifyFlow(complaint.Id,null);
                    }
                    if(complaint.Toxic_Substances__c)
                    {
                        LaunchUpdateToxicsRegionFlow(complaint.Id, complaint.Complaint_Location_County__c);
                    }  
                }  
            }            
            TriggerHandler.bypass('ComplaintTriggerHandler');            
            update complaint;
            TriggerHandler.clearBypass('ComplaintTriggerHandler');                        
        }
    }
    
    public static void CreateToxicsAndWaterAssignments(Set<id> complaintIds)
    {
         List<Complaints__c> complaints = [SELECT Id, Complaint_Location_County__c, Regional_Water_Board__c, Water_Rights__c, Drinking_Water__c,  Water__c, Toxic_Substances__c FROM Complaints__c WHERE Id in: complaintIds FOR UPDATE];

        for(Complaints__c complaint : complaints)
        {
            if(complaint.Toxic_Substances__c)
            {
                LaunchUpdateToxicsRegionFlow(complaint.Id, complaint.Complaint_Location_County__c);
            }
            if(complaint.Water__c)
            {
                LaunchSetWaterContactAndNotifyFlow(complaint.Id,null);
            }
        } 
    }
    
    @future(callout=true)
    public static void CreateComplaintPDF(Set<id> complaintIds)
    {
        for(Id complaintId : complaintIds)
        {
            string complaintPDFUrl = OrgURLHelper.GetSiteUrl('ExternalPartnerPortal');
            complaintPdfUrl = complaintPdfUrl + 'complaintpdf?id=';
            complaintPdfUrl = complaintPdfUrl + complaintId;            
            PageReference pdf = new PageReference(complaintPdfUrl);
            system.debug('pdf:  ' + pdf.getUrl());
            ContentVersion contentVersion = new ContentVersion();
            contentVersion.Title = 'ComplaintOriginalSubmission';
            contentVersion.PathOnClient = 'ComplaintOriginalSubmission.pdf';
            if(!Test.isRunningTest())
            {
                contentVersion.VersionData = pdf.getContentAsPDF();
            }
            else
            {
                Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
                contentVersion.VersionData=bodyBlob;
            }
            contentVersion.IsMajorVersion = true;
            insert contentVersion;
            contentVersion = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id LIMIT 1];
            ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
            contentDocumentLink.ContentDocumentId = contentVersion.ContentDocumentId;
            contentDocumentLink.LinkedEntityId = complaintId;
            contentDocumentLink.ShareType = 'I';
            contentDocumentLink.Visibility = 'AllUsers';
            insert contentDocumentLink;
        }
    }

    @TestVisible
    private static string LaunchUpdateToxicsRegionFlow(string complaintId, string complaintCounty)
    {
        system.debug('complaintId:  ' + complaintId);
        //Instance of the Flow
        Map<String, Object> myMap = new Map<String, Object>();
        myMap.put('ComplaintCounty', complaintCounty);
        myMap.put('ComplaintId', complaintId);
        Flow.Interview.Create_Toxic_Substances_Assignment myFlow = new Flow.Interview.Create_Toxic_Substances_Assignment(myMap);
        myFlow.start(); 
        string returnValue = (string)myFlow.getVariableValue('AssignmentId');
        system.debug('returnValue:  ' + returnValue);
        return returnValue;
    }
    
    @TestVisible
    private static void LaunchSetWaterContactAndNotifyFlow(string complaintId, string region)
    {
        //Instance of the Flow
        Map<String, Object> myMap = new Map<String, Object>();
        myMap.put('ComplaintId', complaintId);
        myMap.put('Region', region);
        Flow.Interview.Create_Water_Assignment myFlow = new Flow.Interview.Create_Water_Assignment(myMap);
        myFlow.start(); 
    }
}