unpackaged/objects/Complaint_Assignment__c.object
<CustomObject>
    <description>Object to track BDO level status and &quot;ownership&quot;</description>
    <fields>
        <fullName>Closure_Comments__c</fullName>
        <label>Closure Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Closure_Reason__c</fullName>
        <label>Closure Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insufficient Information</fullName>
                </value>
                <value>
                    <fullName>Outside of Agency&apos;s Jurisdiction</fullName>
                </value>
                <value>
                    <fullName>Transferred to External Agency</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Investigated by BDO</fullName>
                </value>
                <value>
                    <fullName>Investigated by External Agency</fullName>
                </value>
                <value>
                    <fullName>Unsubstantiated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint</label>
        <referenceTo>Complaints__c</referenceTo>
        <relationshipLabel>Complaint Assignments</relationshipLabel>
        <relationshipName>Complaint_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;New&apos;</defaultValue>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Referred</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Pesticides</fullName>
                </value>
                <value>
                    <fullName>Solid Waste</fullName>
                </value>
                <value>
                    <fullName>Toxic Substances</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint Assignment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Complaint Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Complaint_Assignment_Group__c.object
<CustomObject>
    <description>Object to recognize the different groups that can work on complaints.</description>
    <fields>
        <fullName>Lookup_Value__c</fullName>
        <label>Lookup Value</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Pesticides</fullName>
                </value>
                <value>
                    <fullName>Solid Waste/CalRecycle</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Division of Drinking Water</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Division of Water Quality</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Division of Water Rights</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Office of Enforcement</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Region 1 - North Coast</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Region 2 - San Francisco Bay</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Region 3 - Central Coast</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Region 4 - Los Angeles</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Region 5 - Central Valley</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Region 6 - Lahontan</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Region 7 - Colorado River Basin</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Region 8 - Santa Ana</fullName>
                </value>
                <value>
                    <fullName>SWRCB - Region 9 - San Diego</fullName>
                </value>
                <value>
                    <fullName>Department of Toxic Substances Control</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Department of Toxic Substances Control - Northern</fullName>
                </value>
                <value>
                    <fullName>Department of Toxic Substances Control - Southern</fullName>
                </value>
                <value>
                    <fullName>Drinking Water</fullName>
                </value>
                <value>
                    <fullName>Water Rights</fullName>
                </value>
                <value>
                    <fullName>DPR</fullName>
                </value>
                <value>
                    <fullName>DTSC - Southern</fullName>
                </value>
                <value>
                    <fullName>Region 1</fullName>
                </value>
                <value>
                    <fullName>Region 2</fullName>
                </value>
                <value>
                    <fullName>Region 3</fullName>
                </value>
                <value>
                    <fullName>Region 4</fullName>
                </value>
                <value>
                    <fullName>Region 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Pesticides</fullName>
                </value>
                <value>
                    <fullName>Solid Waste</fullName>
                </value>
                <value>
                    <fullName>Toxic Substances</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint Assignment Group</label>
    <nameField>
        <label>Complaint Assignment Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaint Assignment Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>Air__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you have a general air pollution complaint, which includes open burning, stationary source emissions, fugitive dust emissions, and gasoline nozzles.</inlineHelpText>
        <label>Air</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Regional_Water_Board__c</fullName>
        <label>Regional Water Board</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solid_Waste__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark this check box if the complaint is a solid waste issue</inlineHelpText>
        <label>Solid Waste</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Open&quot;</defaultValue>
        <inlineHelpText>Under Review: Initial investigation is in progress or trying to Refer
Transferred:  Complaint has been assigned internally
Referred:  Complaint has been assigned and confirmed to an external partner
Closed/Actions Taken:  Closed for Cal EPA</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Water_Quality__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Problems  or pollution in a stream, river, lake, wetlands, bay, groundwater basin, or the ocean resulting from discharges of polluted water or stormwater, or from other activities such as construction, grading, and excavations.</inlineHelpText>
        <label>Water Quality</label>
        <type>Checkbox</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <recordTypes>
        <fullName>Air</fullName>
        <active>true</active>
        <description>Air Complaint Record Type.</description>
        <label>Air</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <description>Parent complaint Record Type..</description>
        <label>Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Water</fullName>
        <active>true</active>
        <description>Water Complaint Record Type.</description>
        <label>Water</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Disable_All_Flows__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Value</label>
        <type>Checkbox</type>
    </fields>
    <label>Disable All Flows</label>
</CustomObject>

unpackaged/classes/FlowUnitTests.cls
@isTest
public with sharing class FlowUnitTests 
{
    //Close_Complaint_After_All_Assignments_are_Closed
    public static testMethod void CloseComplaintAfterAllAssignmentsAreClosed_AllClosed()
    {
        //Arrange
        string expected = 'Closed';

        Complaint_Assignment_Group__c complaintAssignmentGroup1 = new Complaint_Assignment_Group__c(Name='Air Resources Board', Lookup_Value__c='Air', Type__c = 'Air');
        insert complaintAssignmentGroup1;        

        Complaint_Assignment_Group__c complaintAssignmentGroup2 = new Complaint_Assignment_Group__c(Name='California Department of Resources Recycling and Recovery (CalRecycle)', Lookup_Value__c='Solid Waste/CalRecycle', Type__c = 'Solid Waste');
        insert complaintAssignmentGroup2;        


        RecordType parentComplaintRecordType = [SELECT Id, Name, SobjectType FROM RecordType WHERE SobjectType = 'Complaints__c' AND Name =: 'Parent' Limit 1 ];
        Complaints__c complaint = new Complaints__c(RecordTypeId = parentComplaintRecordType.Id, Air__c = true,Solid_Waste__c = true);
        insert complaint;        
        
        List<Complaint_Assignment__c> assignments = [SELECT Id,Status__c,Closure_Reason__c,Closure_Comments__c FROM Complaint_Assignment__c WHERE Complaint__c=:complaint.Id];
        
        //Act
        for(Complaint_Assignment__c assignment : assignments)
        {
            assignment.Status__c = 'Closed';
            assignment.Closure_Reason__c = 'Other';
            assignment.Closure_Comments__c = 'Closed For Test';
        }
        Test.startTest();
        update assignments;
        Test.stopTest();
        complaint = [SELECT Id, Status__c FROM Complaints__c WHERE Id=:complaint.Id];
        string actual = complaint.Status__c;

        //Assert
        system.assertEquals(expected, actual);
    }

    //Create_Toxic_Substances_Assignment
     public static testMethod void CreateToxicSubstancesAssignmentNorthern()
    {
        //Arrange
        integer expected = 1;



        Complaint_Assignment_Group__c complaintAssignmentGroup = new Complaint_Assignment_Group__c(Name='Department of Toxic Substances Control (Northern)', Lookup_Value__c='Department of Toxic Substances Control - Northern', Type__c = 'Toxic Substances');
        insert complaintAssignmentGroup;        

        RecordType parentComplaintRecordType = [SELECT Id, Name, SobjectType FROM RecordType WHERE SobjectType = 'Complaints__c' AND Name =: 'Parent' Limit 1 ];
        Complaints__c complaint = new Complaints__c(RecordTypeId = parentComplaintRecordType.Id);
        insert complaint;        
        
        //Act
        Test.startTest();
        ComplaintManager.LaunchUpdateToxicsRegionFlow(complaint.Id, 'Sacramento County');
        Test.stopTest();
        List<Complaint_Assignment__c> assignments = [SELECT Id FROM Complaint_Assignment__c WHERE Complaint__c=:complaint.Id AND Type__c='Toxic Substances'];
        integer actual = assignments.Size();
        //Assert
        system.assertEquals(expected, actual);
    }

    public static testMethod void CreateToxicSubstancesAssignmentSouthern()
    {
        //Arrange
        integer expected = 1;
        
        Complaint_Assignment_Group__c complaintAssignmentGroup = new Complaint_Assignment_Group__c(Name='Department of Toxic Substances Control (Southern)', Lookup_Value__c='Department of Toxic Substances Control - Southern', Type__c = 'Toxic Substances');
        insert complaintAssignmentGroup;        

        RecordType parentComplaintRecordType = [SELECT Id, Name, SobjectType FROM RecordType WHERE SobjectType = 'Complaints__c' AND Name =: 'Parent' Limit 1 ];
        Complaints__c complaint = new Complaints__c(RecordTypeId = parentComplaintRecordType.Id);
        insert complaint;        
        
        
        
        //Act
        Test.startTest();
        ComplaintManager.LaunchUpdateToxicsRegionFlow(complaint.Id, 'Los Angeles County');
        Test.stopTest();
        List<Complaint_Assignment__c> assignments = [SELECT Id FROM Complaint_Assignment__c WHERE Complaint__c=:complaint.Id AND Type__c='Toxic Substances'];
        integer actual = assignments.Size();
        //Assert
        system.assertEquals(expected, actual);
    }

    public static testMethod void CreateToxicSubstancesAssignmentUnknown()
    {
        //Arrange
        integer expected = 1;

        Complaint_Assignment_Group__c complaintAssignmentGroup = new Complaint_Assignment_Group__c(Name='Department of Toxic Substances Control', Lookup_Value__c='Department of Toxic Substances Control', Type__c = 'Toxic Substances');
        insert complaintAssignmentGroup;        

        RecordType parentComplaintRecordType = [SELECT Id, Name, SobjectType FROM RecordType WHERE SobjectType = 'Complaints__c' AND Name =: 'Parent' Limit 1 ];
        Complaints__c complaint = new Complaints__c(RecordTypeId = parentComplaintRecordType.Id);
        insert complaint;        
        
        
        
        //Act
        Test.startTest();
        ComplaintManager.LaunchUpdateToxicsRegionFlow(complaint.Id, '');
        Test.stopTest();
        List<Complaint_Assignment__c> assignments = [SELECT Id FROM Complaint_Assignment__c WHERE Complaint__c=:complaint.Id AND Type__c='Toxic Substances'];
        integer actual = assignments.Size();
        //Assert
        system.assertEquals(expected, actual);
    }

    public static testMethod void CreateWaterAssignmentRegion1()
    {
        //Arrange
        integer expected = 1;
        
        insert new Disable_All_Flows__c(SetupOwnerId=UserInfo.getOrganizationId(), Value__c=false);

        Complaint_Assignment_Group__c complaintAssignmentGroup = new Complaint_Assignment_Group__c(Name='State of California North Coast Regional Water Quality Control Board', Lookup_Value__c='SWRCB - Region 1 - North Coast', Type__c = 'Water');
        insert complaintAssignmentGroup;        


        RecordType parentComplaintRecordType = [SELECT Id, Name, SobjectType FROM RecordType WHERE SobjectType = 'Complaints__c' AND Name =: 'Parent' Limit 1 ];
        Complaints__c complaint = new Complaints__c(RecordTypeId = parentComplaintRecordType.Id, Water_Quality__c = true, Regional_Water_Board__c='Region 1');
        insert complaint;        
        
        
        
        //Act
        Test.startTest();
        ComplaintManager.LaunchSetWaterContactAndNotifyFlow(complaint.Id, 'Region 1');
        Test.stopTest();
        List<Complaint_Assignment__c> assignments = [SELECT Id FROM Complaint_Assignment__c WHERE Complaint__c=:complaint.Id AND Type__c='Water'];
        integer actual = assignments.Size();
        //Assert
        system.assertEquals(expected, actual);
    }
}