unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>Air__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you have a general air pollution complaint, which includes open burning, stationary source emissions, fugitive dust emissions, and gasoline nozzles.</inlineHelpText>
        <label>Air</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Anonymous__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If the person submitting the complaint would like to remain anonymous, check this box here.</inlineHelpText>
        <label>Anonymous</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_Address__c</fullName>
        <inlineHelpText>Complaint location address or intersection</inlineHelpText>
        <label>Complaint Location Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_City__c</fullName>
        <inlineHelpText>City of the complaint location</inlineHelpText>
        <label>Complaint Location City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_State__c</fullName>
        <label>Complaint Location State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California</fullName>
                    <default>true</default>
                    <label>California</label>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Complaint_Location_Zip_Code__c</fullName>
        <inlineHelpText>Zip Code where the complaint occurred</inlineHelpText>
        <label>Complaint Location Zip Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Referring_Agency__c</fullName>
        <label>Referring Agency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referring_Email_Address__c</fullName>
        <description>Email address of the person (usually outside Cal EPA) that entered this complaint</description>
        <label>Person Referring&apos;s Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referring_Name__c</fullName>
        <label>Name of Person Referring</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Contact_Email__c</fullName>
        <label>Temp Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Unknown_Date_of_Occurrence__c</fullName>
        <label>Unknown Date of Occurrence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In the Last 7 Days</fullName>
                </value>
                <value>
                    <fullName>In the Last 30 Days</fullName>
                </value>
                <value>
                    <fullName>A Long Time Ago</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Exact Date</fullName>
                    <default>true</default>
                    <label>Exact Date</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <recordTypes>
        <fullName>Pesticides</fullName>
        <active>true</active>
        <description>Pesticide complaint Record Type.</description>
        <label>Pesticides</label>
    </recordTypes>
    <recordTypes>
        <fullName>Water</fullName>
        <active>true</active>
        <description>Water Complaint Record Type.</description>
        <label>Water</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Custom_Links__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To be able to change custom links on the public facing web page</description>
    <fields>
        <fullName>Web_Link__c</fullName>
        <label>Web Link</label>
        <type>Url</type>
    </fields>
    <label>Custom Links</label>
</CustomObject>

unpackaged/classes/ComplaintController_Test.cls
@isTest
public class ComplaintController_Test {
    public static testMethod void myUnitTest(){
        test.startTest();
        /*List<Custom_Links__c> links = new List<Custom_Links__c>();
        Custom_Links__c cl = new Custom_Links__c();
        cl.Name = 'Water Waste';
        cl.Web_Link__c = 'http://www.test.com';
        links.add(cl);
        cl = new Custom_Links__c();
        cl.Name = 'Prop65';
        cl.Web_Link__c = 'http://www.test.com';
        links.add(cl);
        cl = new Custom_Links__c();
        cl.Name = 'Pesticides - CAC Directory';
        cl.Web_Link__c = 'http://www.test.com';
        links.add(cl);
        insert links;
        */
               
        Complaints__c c = new Complaints__c();
        c.Air__c = true;
        c.Complaint_Location_Address__c = '1001 I Street';
        c.Complaint_Location_City__c = 'Sacramento'; 
        c.Complaint_Location_State__c = 'CA';
        c.Complaint_Location_Zip_Code__c = '95812';
        
        
        test.setCurrentPage(new PageReference('/apex/Complaint'));
        ApexPages.Standardcontroller sc = new ApexPages.StandardController(c);
        ComplaintController cc = new ComplaintController(sc);
        
        cc.getComplaint();
        cc.sameAddress = 'true';
        cc.complaint.Air__c = true;
        cc.complaint.Complaint_Location_Address__c = '1001 I Street';
        cc.complaint.Complaint_Location_City__c = 'Sacramento'; 
        cc.complaint.Complaint_Location_State__c = 'CA';
        cc.complaint.Complaint_Location_Zip_Code__c = '95812';
        cc.personContact.LastName = 'test';
        cc.complaint.Temp_Contact_Email__c = 'test@test.com';
        cc.getAccount();
        cc.submittedDate = '2016-02-28';
        cc.getStates();
        cc.pageCheck();
        cc.getContact();
        cc.getCustomLinks();
        cc.updateSameAddress();
        cc.updateAnonymous();
        cc.emeregency();
        cc.step1();
        cc.step2();

        cc.step2();
        cc.updateAttachmentMap();
        cc.step3();
        cc.complaint.Description__c = 'test description';
        cc.complaint.Unknown_Date_of_Occurrence__c = 'Exact Date';
        cc.occuranceDateTime = '2/1/2016 12:01:01 PM';
        cc.step3();
        
        cc.step4();
        cc.account.PersonEmail = 'test@test.com';
        cc.personContact.firstName = 'test';
        cc.step4();
        cc.complaint.Referring_Name__c = 'test';
        cc.complaint.Referring_Agency__c = 'test';
        cc.complaint.Referring_Email_Address__c = 'test@test.com';
        cc.step4();
        cc.complaint.Anonymous__c = true;
        
        Attachment att = new Attachment();
        att.Name = 'test.txt';
        att.Body = blob.valueOf('test test test');
        att.ContentType = 'txt';
        cc.attachment = att;
        cc.addAttachment();
        att = new Attachment();
        att.Name = 'test.txt';
        att.Body = blob.valueOf('test test test');
        att.ContentType = 'txt';
        cc.attachment = att;
        cc.addAttachment();
        Set<Id> aIds = new Set<Id>();
        for(string a : cc.attachmentMap.keySet()){
            aIds.add(a);
            cc.rAttachmentId = a;
        }
        
        cc.removeAttachment();
        cc.step4();
        
        cc.cancel();
        
        
        test.stopTest();
    }
}