unpackaged/objects/Complaints__c.object
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Finding__c.object
<CustomObject>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Finding</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Finding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Referral__c.object
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{00000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/FindingManagerTests.cls
@isTest
public class FindingManagerTests 
{
	@isTest static void TestRetrieveConfirmationEmails()
	{
		//Arrange
		integer expected = 1;

		Account testAccount = UnitTestHelper.CreateTestAccount();
		Contact testContact = UnitTestHelper.CreateTestCalEPAPartnerContact(testAccount.Id, 'TestContact@TestAccount.edu');
		Complaints__c testComplaint = UnitTestHelper.CreateTestComplaint();
		Referral__c testReferral = UnitTestHelper.CreateTestReferral(testComplaint.Id, testAccount.Id,testContact.Id);
		Finding__c testFinding = UnitTestHelper.CreateTestFinding(testComplaint.Id, testReferral.Id, testContact.Id);
		
		//Act
		List<Messaging.SingleEmailMessage> actualMessages = FindingManager.RetrieveConfirmationEmails(new Set<Id>{testFinding.Id});
		integer actual = actualMessages.Size();

		//Assert
		System.AssertEquals(expected , actual);

	}	
	@isTest static void TestRetrieveNotificaitonEmails()
	{
		//Arrange
		integer expected = 1;

		Account testAccount = UnitTestHelper.CreateTestAccount();
		Contact testContact = UnitTestHelper.CreateTestCalEPAPartnerContact(testAccount.Id, 'TestContact@TestAccount.edu');
		Complaints__c testComplaint = UnitTestHelper.CreateTestComplaint();
		Referral__c testReferral = UnitTestHelper.CreateTestReferral(testComplaint.Id, testAccount.Id,'');
		Finding__c testFinding = UnitTestHelper.CreateTestFinding(testComplaint.Id, testReferral.Id, testContact.Id);
		
		//Act
		List<Messaging.SingleEmailMessage> actualMessages = FindingManager.RetrieveNotificaitonEmails(new Set<Id>{testFinding.Id});
		integer actual = actualMessages.Size();
		
		//Assert
		System.AssertEquals(expected , actual); 
	}
}