unpackaged/objects/Complaints__c.object
<CustomObject>
    <fields>
        <fullName>Census_Tract_Number__c</fullName>
        <label>Census Tract Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_Address__c</fullName>
        <inlineHelpText>Complaint location address or intersection</inlineHelpText>
        <label>Complaint Location Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_City__c</fullName>
        <inlineHelpText>City of the complaint location</inlineHelpText>
        <label>Complaint Location City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Location_County__c</fullName>
        <inlineHelpText>County where the complaint occurred</inlineHelpText>
        <label>Complaint Location County</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alameda County</fullName>
                </value>
                <value>
                    <fullName>Alpine County</fullName>
                </value>
                <value>
                    <fullName>Amador County</fullName>
                </value>
                <value>
                    <fullName>Butte County</fullName>
                </value>
                <value>
                    <fullName>Calaveras County</fullName>
                </value>
                <value>
                    <fullName>Colusa County</fullName>
                </value>
                <value>
                    <fullName>Contra Costa County</fullName>
                </value>
                <value>
                    <fullName>Del Norte County</fullName>
                </value>
                <value>
                    <fullName>El Dorado County</fullName>
                </value>
                <value>
                    <fullName>Fresno County</fullName>
                </value>
                <value>
                    <fullName>Glenn County</fullName>
                </value>
                <value>
                    <fullName>Humboldt County</fullName>
                </value>
                <value>
                    <fullName>Imperial County</fullName>
                </value>
                <value>
                    <fullName>Inyo County</fullName>
                </value>
                <value>
                    <fullName>Kern County</fullName>
                </value>
                <value>
                    <fullName>Kings County</fullName>
                </value>
                <value>
                    <fullName>Lake County</fullName>
                </value>
                <value>
                    <fullName>Lassen County</fullName>
                </value>
                <value>
                    <fullName>Los Angeles County</fullName>
                </value>
                <value>
                    <fullName>Madera County</fullName>
                </value>
                <value>
                    <fullName>Marin County</fullName>
                </value>
                <value>
                    <fullName>Mariposa County</fullName>
                </value>
                <value>
                    <fullName>Mendocino County</fullName>
                </value>
                <value>
                    <fullName>Merced County</fullName>
                </value>
                <value>
                    <fullName>Modoc County</fullName>
                </value>
                <value>
                    <fullName>Mono County</fullName>
                </value>
                <value>
                    <fullName>Monterey County</fullName>
                </value>
                <value>
                    <fullName>Napa County</fullName>
                </value>
                <value>
                    <fullName>Nevada County</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Complaint_Location_State__c</fullName>
        <label>Complaint Location State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California</fullName>
                    <default>true</default>
                    <label>California</label>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Complaint_Location_Zip_Code__c</fullName>
        <inlineHelpText>Zip Code where the complaint occurred</inlineHelpText>
        <label>Complaint Location Zip Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COMP-{00000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/ComplaintTriggerHandlerTests.cls
@isTest
public class ComplaintTriggerHandlerTests 
{
    /*static testMethod void beforeInsert_ParentComplaint_ExpectAgencyOwner()
    {
        system.debug('hello world');
        //Arrange
        string expected = 'Agency';
        Complaints__c complaint = new Complaints__c();

        //Act
        Test.startTest();        
        insert complaint;
        Test.stopTest();
        
        Complaints__c retrieved = [SELECT Id, OwnerId, RecordTypeId FROM Complaints__c WHERE Id =: complaint.Id];
        Group ownerQueue = new QueueManager().GetQueueById(retrieved.OwnerId);
        string actual = ownerQueue.Name;
        
        //Assert
        System.assertEquals(expected, actual); 
    }*/
    
    
    static testMethod void afterInsert_AddressProvided_ExpectedStreetAddress()
    {
        //Arrange
        string expected = '1600 Pennsylvania Avenue';
        Complaints__c complaint = new Complaints__c(Complaint_Location_Address__c = '987 Elm St', Complaint_Location_City__c = 'A City', Complaint_Location_State__c = 'A State', Complaint_Location_Zip_Code__c = '12345');
        

        //Act
        Test.startTest();        
        insert complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Complaint_Location_Address__c FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Complaint_Location_Address__c;

        //Assert
        System.assertEquals(expected, actual);                          
    }
    
    static testMethod void afterInsert_AddressProvided_ExpectedCity()
    {
        //Arrange
        string expected = 'AnyTown';
        Complaints__c complaint = new Complaints__c(Complaint_Location_Address__c = '987 Elm St', Complaint_Location_City__c = 'A City', Complaint_Location_State__c = 'A State', Complaint_Location_Zip_Code__c = '12345');
        

        //Act
        Test.startTest();        
        insert complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Complaint_Location_City__c FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Complaint_Location_City__c;

        //Assert
        System.assertEquals(expected, actual);                          
    }
    
    static testMethod void afterInsert_AddressProvided_ExpectedState()
    {
        //Arrange
        string expected = 'Florida';
        Complaints__c complaint = new Complaints__c(Complaint_Location_Address__c = '987 Elm St', Complaint_Location_City__c = 'A City', Complaint_Location_State__c = 'A State', Complaint_Location_Zip_Code__c = '12345');
        

        //Act
        Test.startTest();        
        insert complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Complaint_Location_State__c FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Complaint_Location_State__c;

        //Assert
        System.assertEquals(expected, actual);                          
    }                                                     

    static testMethod void afterInsert_AddressProvided_ExpectedZipCode()
    {
        //Arrange
        string expected = '90210';
        Complaints__c complaint = new Complaints__c(Complaint_Location_Address__c = '987 Elm St', Complaint_Location_City__c = 'A City', Complaint_Location_State__c = 'A State', Complaint_Location_Zip_Code__c = '12345');
        

        //Act
        Test.startTest();        
        insert complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Complaint_Location_Zip_Code__c FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Complaint_Location_Zip_Code__c;

        //Assert
        System.assertEquals(expected, actual);                          
    }                                                                         
    
    static testMethod void afterInsert_AddressProvided_ExpectedCounty()
    {
        //Arrange
        string expected = 'Madison County';
        Complaints__c complaint = new Complaints__c(Complaint_Location_Address__c = '987 Elm St', Complaint_Location_City__c = 'A City', Complaint_Location_State__c = 'A State', Complaint_Location_Zip_Code__c = '12345');
        

        //Act
        Test.startTest();        
        insert complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Complaint_Location_County__c FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Complaint_Location_County__c;

        //Assert
        System.assertEquals(expected, actual);                          
    }                                                     

    static testMethod void afterInsert_AddressProvided_ExpectedCensusTract()
    {
        //Arrange
        string expected = '6019001500';
        Complaints__c complaint = new Complaints__c(Complaint_Location_Address__c = '987 Elm St', Complaint_Location_City__c = 'A City', Complaint_Location_State__c = 'A State', Complaint_Location_Zip_Code__c = '12345');
        

        //Act
        Test.startTest();        
        insert complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Census_Tract_Number__c FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Census_Tract_Number__c;

        //Assert
        System.assertEquals(expected, actual);                          
    }

    
    static testMethod void afterUpdate_AddressChanged_ExpectUpdatedStreetAddress()
    {
        //Arrange
        string expected = '1600 Pennsylvania Avenue';
        Complaints__c complaint = new Complaints__c();
        

        //Act
        Test.startTest();        
        insert complaint;
        complaint.Complaint_Location_Address__c = '987 Elm St';
        complaint.Complaint_Location_City__c = 'A City';
        complaint.Complaint_Location_State__c = 'A State';
        complaint.Complaint_Location_Zip_Code__c = '12345';
        TriggerManager.RunAfterUpdate = true;
        update complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Complaint_Location_Address__c FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Complaint_Location_Address__c;

        //Assert
        System.assertEquals(expected, actual);                          
    }
    
    static testMethod void afterUpdate_AddressChanged_ExpectUpdatedCity()
    {
        //Arrange
        string expected = 'AnyTown';
        Complaints__c complaint = new Complaints__c();
        

        //Act
        Test.startTest();        
        insert complaint;
        complaint.Complaint_Location_Address__c = '987 Elm St';
        complaint.Complaint_Location_City__c = 'A City';
        complaint.Complaint_Location_State__c = 'A State';
        complaint.Complaint_Location_Zip_Code__c = '12345';
        TriggerManager.RunAfterUpdate = true;
        update complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Complaint_Location_City__c  FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Complaint_Location_City__c ;

        //Assert
        System.assertEquals(expected, actual);                          
    }
    
    static testMethod void afterUpdate_AddressChanged_ExpectUpdatedState()
    {
        //Arrange
        string expected = 'Florida';
        Complaints__c complaint = new Complaints__c();
        

        //Act
        Test.startTest();        
        insert complaint;
        complaint.Complaint_Location_Address__c = '987 Elm St';
        complaint.Complaint_Location_City__c = 'A City';
        complaint.Complaint_Location_State__c = 'A State';
        complaint.Complaint_Location_Zip_Code__c = '12345';
        TriggerManager.RunAfterUpdate = true;
        update complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Complaint_Location_State__c  FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Complaint_Location_State__c ;

        //Assert
        System.assertEquals(expected, actual);                          
    }
    
    static testMethod void afterUpdate_AddressChanged_ExpectUpdatedZipCode()
    {
        //Arrange
        string expected = '90210';
        Complaints__c complaint = new Complaints__c();
        

        //Act
        Test.startTest();        
        insert complaint;
        complaint.Complaint_Location_Address__c = '987 Elm St';
        complaint.Complaint_Location_City__c = 'A City';
        complaint.Complaint_Location_State__c = 'A State';
        complaint.Complaint_Location_Zip_Code__c = '12345';
        TriggerManager.RunAfterUpdate = true;
        update complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Complaint_Location_Zip_Code__c FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Complaint_Location_Zip_Code__c;

        //Assert
        System.assertEquals(expected, actual);                          
    }
    
    static testMethod void afterUpdate_AddressChanged_ExpectUpdatedCounty()
    {
        //Arrange
        string expected = 'Madison County';
        Complaints__c complaint = new Complaints__c();
        

        //Act
        Test.startTest();        
        insert complaint;
        complaint.Complaint_Location_Address__c = '987 Elm St';
        complaint.Complaint_Location_City__c = 'A City';
        complaint.Complaint_Location_State__c = 'A State';
        complaint.Complaint_Location_Zip_Code__c = '12345';
        TriggerManager.RunAfterUpdate = true;
        update complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Complaint_Location_County__c FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Complaint_Location_County__c;

        //Assert
        System.assertEquals(expected, actual);                          
    }
   
    static testMethod void afterUpdate_AddressChanged_ExpectUpdatedCensusTract()
    {
        //Arrange
        string expected = '6019001500';
        Complaints__c complaint = new Complaints__c();
        

        //Act
        Test.startTest();        
        insert complaint;
        complaint.Complaint_Location_Address__c = '987 Elm St';
        complaint.Complaint_Location_City__c = 'A City';
        complaint.Complaint_Location_State__c = 'A State';
        complaint.Complaint_Location_Zip_Code__c = '12345';
        TriggerManager.RunAfterUpdate = true;
        update complaint;
        Test.stopTest();
        Complaints__c retrieved = [SELECT Id, Census_Tract_Number__c   FROM Complaints__c WHERE Id =: complaint.Id];
        string actual = retrieved.Census_Tract_Number__c  ;

        //Assert
        System.assertEquals(expected, actual);                          
    }
    
}