unpackaged/objects/Finding__c.object
<CustomObject>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Finding</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Finding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Findings Received</fullName>
                </value>
                <value>
                    <fullName>Awaiting Findings</fullName>
                    <default>true</default>
                    <label>Awaiting Findings</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{00000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/FindingTriggerHandler.cls
public with sharing class FindingTriggerHandler  extends TriggerHandler 
{
	public FindingTriggerHandler() 
	{
		
	}

	protected override void beforeInsert()
    {

	}

	protected override void afterInsert()
    {
		Set<Id> newIds = new Set<Id>();
		Set<Id> referralIdsToUpdate = new Set<Id>();
		for(Finding__c finding : (List<Finding__c>)trigger.new)
		{
			newIds.Add(finding.Id);
			if(finding.Referral__c != null)
			{
				referralIdsToUpdate.Add(finding.Referral__c);
			}
		}
		List<Referral__c> referralsToUpdate = [SELECT Id, Status__c FROM Referral__c WHERE Id in: referralIdsToUpdate];
		for(Referral__c referral : referralsToUpdate)
		{
			referral.Status__c = 'Findings Received';
		}
		update referralsToUpdate;
		if(!Test.isRunningTest())
        {
			FindingManager.SendConfirmationEmail(newIds);
			FindingManager.SendNotificationEmail(newIds);
		}
		
	}

	protected override void beforeUpdate()
    {

	}

	protected override void afterUpdate()
    {
		Set<Id> referralIdsToUpdate = new Set<Id>();
		for(Finding__c finding : (List<Finding__c>)trigger.new)
		{
			if(finding.Referral__c != null)
			{
				referralIdsToUpdate.Add(finding.Referral__c);
			}
		}
		List<Referral__c> referralsToUpdate = [SELECT Id, Status__c FROM Referral__c WHERE Id in: referralIdsToUpdate];
		for(Referral__c referral : referralsToUpdate)
		{
			referral.Status__c = 'Findings Received';
		}
		update referralsToUpdate;
	}
}